### ISSUE TITLE
Add an Appveyor build

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/HELICS-src#10]
How possible is it to add an Appveyor build to the integration testing?

**Comment by nightlark** [comment]
Should be fairly easy to get it building on Appveyor, since you've already building it regularly on Windows.

**Comment by phlptp** [comment]
The only potential problem is likely to be the zmq library, not sure if you want to use the autobuild or figure out how to get that installed and linked.

**Comment by nightlark** [comment]
I think autobuild would be easier, but the build time would be longer. If the build takes a long time, caching the third party lib directory would help (but one more thing to update if we change the version it depends on in the future).

**Comment by phlptp** [comment]
Probably good to keep the autobuild on then as I suspect most windows users who build it will use that.

**Comment by nightlark** [comment]
Right now, appveyor builds are only running when triggered manually. I guess since I can't change repo settings, the webhook to trigger builds didn't get added. Adding https://ci.appveyor.com/api/github/webhook?id=gjf8l7eed0a1b8f6 should make appveyor build on each commit.

**Comment by kdheepak** [comment]
Appveyor build hook is working. Build on @nightlark's account. We would have to create a new appveyor account to have it under GMLC-TDC.
