### ISSUE TITLE
Windows installer

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/HELICS-src#106]
Construct a windows installer to make it really easy on Windows systems

**Comment by kdheepak** [comment]
Having a mac dmg would also be great.

**Comment by phlptp** [comment]
I am hoping we can work through the CPACK stuff to be able to automatically generate windows installers mac dmg's and some sort of linux binary packages for Debian and Redhat.  Maybe even SNAP packages.  But I think windows is probably the hardest to build with people less familiar with software development so should be the first installer.  I think the others should have their own issues.

**Comment by phlptp** [comment]
This is also mostly just to put a notice on the agenda in the projects.  Not anticipating much progress in the next two months.

**Comment by phlptp** [comment]
@kdheepak suggested "We should consider building a package using https://chocolatey.org/ for helics"

**Comment by phlptp** [comment]
The CPACK instructions seem to be operations so at the next release we should package up a windows installer binary.  we should also revisit the chocolatey package at some point in the future.
