### ISSUE TITLE
#pragma deprecated warnings from boost

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/HELICS-src#108]
```
In file included from /home/travis/build/GMLC-TDC/HELICS-src/dependencies/boost/include/boost/iostreams/detail/is_dereferenceable.hpp:12:0,
                 from /home/travis/build/GMLC-TDC/HELICS-src/dependencies/boost/include/boost/iostreams/detail/resolve.hpp:26,
                 from /home/travis/build/GMLC-TDC/HELICS-src/dependencies/boost/include/boost/iostreams/detail/push.hpp:24,
                 from /home/travis/build/GMLC-TDC/HELICS-src/dependencies/boost/include/boost/iostreams/detail/streambuf/indirect_streambuf.hpp:31,
                 from /home/travis/build/GMLC-TDC/HELICS-src/dependencies/boost/include/boost/iostreams/stream_buffer.hpp:22,
                 from /home/travis/build/GMLC-TDC/HELICS-src/dependencies/boost/include/boost/iostreams/stream.hpp:21,
                 from /home/travis/build/GMLC-TDC/HELICS-src/src/helics/application_api/ValueConverter_impl.hpp:37,
                 from /home/travis/build/GMLC-TDC/HELICS-src/tests/helics/application_api/value-converter-tests.cpp:22:
/home/travis/build/GMLC-TDC/HELICS-src/dependencies/boost/include/boost/type_traits/detail/bool_trait_def.hpp:18:78: note: #pragma message: NOTE: Use of this header (bool_trait_def.hpp) is deprecated
 # pragma message("NOTE: Use of this header (bool_trait_def.hpp) is deprecated")
```

this warning is showing up in the build logs due to the use of boost 1.61 in travis and the use of boost::iostreams.  

This is a known issue that was fixed in boost 1.62.    As far as I know the only known fix is to upgrade to boost 1.62 or higher.  The code all works fine.  

The question is whether it is worth upgrading travis to 1.62 or higher to get rid of the warnings.  Costs are that 1.61 is the lowest boost version we support that compiles everything.  so we would loose the earliest supported platform if we upgrade.

**Comment by kdheepak** [comment]
We can add a new target in Travis to compile for Boost 1.61, but use the latest boost in a separate target so that we can look at the logs there. @nightlark thoughts?

**Comment by nightlark** [comment]
We could switch to a newer version of Boost for all of the build configurations except gcc 4.9, and have that build as an earliest supported platform test. I think adding another build target would mean that for commits to master/develop, one of the builds would wait to start until after one of the other builds has finished.

**Comment by phlptp** [comment]
@nightlark I think we should close this issue once we get the newer boost running in travis for the develop branch on all but gcc 4.9 target.  Linked to issue #128.
