### ISSUE TITLE
Add daily build to Travis

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/HELICS-src#111]
In order to ramp up our testing it would be good to get a daily build going of the develop branch.  The first target is running all the tests.  
this would ideally be done with the coverage command and linking with codecov so we can get a good sense of where we have coverage and where it is lacking and track our progress over time.  
the other thing that would be good is running at least some of the tests through valgrind to ensure we not introducing any memory leaks.  I think we are doing ok on this thus far, but it would be good to get continual verification and catch any issues early on

but neither of these needs to be done every commit, so I think it makes sense to run them on develop daily.    We can also probably move the mac builds to daily since they are not executing in a timely manner right now anyway.  #110 already starts to address this

**Comment by nightlark** [comment]
CTest has support for a MemCheck and Coverage stages, so maybe it can be set up to handle running the tests under the right tool to get valgrind/coverage results -- Code coverage looks like a dashboard would be useful for seeing the results (coveralls.io, codecov.io, codacy), the log output on Travis might be enough for results from valgrind.

**Comment by phlptp** [comment]
I have been looking at that and will add something in the near future.  If it becomes a priority let me know.  I am working through different cmake builds with different configurations on linux with a goal of getting the clang-analyzers working in a number of different configurations.

**Comment by phlptp** [comment]
PR #154 adds code coverage flags to project,  I think a little more work might be needed to get that working with one of the online code coverage dashboards
