### ISSUE TITLE
Make HELICS brew installable

### ISSUE THREAD

**Issue by kdheepak** [GMLC-TDC/HELICS-src#125]

**Comment by kdheepak** [comment]
Currently, the following script works to install HELICS on a Mac.

```bash
brew install https://raw.githubusercontent.com/GMLC-TDC/HELICS-src/develop/scripts/brew/helics.rb
```


<img width="1146" alt="screen shot 2018-01-28 at 2 40 07 am" src="https://user-images.githubusercontent.com/1813121/35480839-b363e820-03d4-11e8-8810-1a55a8541d20.png">

This will not install `helics_broker`, `helics_player` or `helics_recorder` to the PATH. It will create the binaries in `/usr/local/Cellar/helics/1.0.0/bin`. It also currently does not install the Python extension. These are improvements to be made.

**Comment by phlptp** [comment]
Just out of curiosity what would we have to do to have something like
```
brew install helics
``` 
or
```
brew install helics-python
```
actually work

and this is pretty cool!

**Comment by phlptp** [comment]
I don't think we want this in the very near future, but what would be involved in getting this into the standard brew libraries so you wouldn't have to enter the tap command first?

**Comment by kdheepak** [comment]
This is what brew recommends as criteria for [Acceptable Formulae](https://github.com/Homebrew/brew/blob/master/docs/Acceptable-Formulae.md) that go into the core. I think we maintain our tap and once we have enough users you can make a PR to the core. The tap is a completely acceptable way to do this. I've installed a lot of packages from taps.

**Comment by kdheepak** [comment]
Users can use the following to install and build the Python extension

```bash
brew install helics --with-python --with-python-include-dir=$(python3-config --prefix)/include/python3.6m/
```

Full instructions will be found in the install instructions documentation page.

**Comment by kdheepak** [comment]
This also adds `helics_broker`, `helics_player` and `helics_recorder` to the PATH.

**Comment by kdheepak** [comment]
Documentation for this has been updated and is located [here](https://gmlc-tdc.github.io/HELICS-src/installation/mac.html).
