### ISSUE TITLE
Xcode 6.4 build on travis changed

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/HELICS-src#138]
The xcode 6.4 build on travis has changed to using boost 1.58.  This is causing the tests to automatically turn off and generate some error.  

the code error is easy to fix, but the other issues require some choices and change

we can either leave it at 1.58 and change some flags so it turns off the tests and doesn't run them
or change it back to a newer boost.  

We do say we support 1.58 in the core so it isn't the worst idea to have one of the builds use it

thoughts?

**Comment by nightlark** [comment]
If we say we support 1.58, we should probably have at least 1 semi-regular build using boost to make sure it still compiles. I noticed the os x problem last night and was going to work on it, but worked on problem with the linux clang builds instead.

**Comment by phlptp** [comment]
I am fine with leaving it at 1.58 we just need to change the flags for that build so it doesn't build the tests and doesn't run anything with ctest

**Comment by kdheepak** [comment]
On osx, we can use `brew update` and then install boost 1.66 if necessary.

**Comment by phlptp** [comment]
I don't actually mind using boost 1.58 in one of the tests,  probably not a bad idea if we are claiming the helics core can compile with that version.  For this build we just need to turn the test builds off so it doesn't trigger the warning message.

**Comment by nightlark** [comment]
I’ll make the changes to turn off tests if we want to keep 1.58

**Comment by phlptp** [comment]
I vote we keep 1.58 and drop the tests,  what is everyone elses opinion?
longer term we probably want some of the examples to run on this platform to make sure everything is working smoothly

**Comment by nightlark** [comment]
We should keep it without the Boost tests, since we say that we support 1.58
