### ISSUE TITLE
use of pragma once

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/HELICS-src#148]
Right now most of the header files we have use a header guard
```
#ifndef _HELICS_HEADER_
#define _HELICS_HEADER_
CODE
#endif
```
The reality is this can be done equivalently with a 
```
#pragma once 
```
in the header files
The minimum versions of all the compilers we support already support this from way earlier versions
I would propose to remove the header guards on many of the hpp files over time and not put them in any new header files.  
This will make the code look cleaner and be easier to maintain and slightly less error prone.  

Exceptions:
Any public header for the C library
Cases where the header file may be identical to those used in other programs.

**Comment by phlptp** [comment]
This issue is to create a discussion vs any immediate actual code change

**Comment by bpalmintier** [comment]
Hmm, I'm certainly most familiar with the `#ifndef` format, but lean toward the `#pragma` because it should be a quick heads up to developers that we are using a more recent C++ standard. 

It also looks like `#pragma` version likely also works with most modern C compilers, so might be OK for the C library too?

See a bit more on [StackOverflow](https://stackoverflow.com/questions/787533/is-pragma-once-a-safe-include-guard)

**Comment by abhyshr** [comment]
I have not used #pragma other than for OpenMP directives but I think this should be fine if most compilers support it. I spoke with the person who handles PETSc installation and compiling and he mentioned the same. Though, he was unsure if all do compilers support it. One caveat he mentioned was having XXXHEADER_H flag allows to check if the flag was set or not to determine whether the header was included or not.

Thanks,
Shri
Ph: (630) 252 0219
www.mcs.anl.gov/~abhyshr<http://www.mcs.anl.gov/~abhyshr>

**Comment by phlptp** [comment]
I have yet to come across a C++14 capable compiler that doesn't support #pragma once,  hypothetically the C interface could be used on an older or unsupported compiler though in all practicality it is unlikely.

**Comment by phlptp** [comment]
Out of curiosity I started digging into all the compilers to see the hypothetical list of all compilers that would possibly support HELICS and minimum versions
GCC 4.9
Clang 3.4 ( I think this would require turning on a few experimental flags and different options)
MSVC 19 (MSVC 2015)
EDG 4.10
Intel (ICC) 16
IBM XLC 13.1.2
Sun C++ 5.15
Cray 8.6
PGI 16.1

of these minimum versions the only one that doesn't support `#pragma once` is PGI.  PGI is owned by NVIDIA and is really meant for writing CUDA kernels and other things like that.  From what I have heard is isn't very good at compiling general source code for general architectures when compared with gcc or clang.  So I doubt we are losing much by not supporting it.

**Comment by abhyshr** [comment]
Phil,
  Go ahead with the changes. Think it should be fine.

Thanks,
Shri
Ph: (630) 252 0219
www.mcs.anl.gov/~abhyshr<http://www.mcs.anl.gov/~abhyshr>

**Comment by phlptp** [comment]
OK,  please use #pragma once on new headers and I or others will slowly remove them from existing headers
I will leave them on the C header files for the time being and a few others that have potential interaction issues.
