### ISSUE TITLE
Simpler set of test cases for CI

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/HELICS-src#15]
Create a simpler(Quicker) set of test cases to run for the CI integration.  We want to run a subset of the test cases on a continual basis to check each commit, like we do with compilation now.  
The goal would be to have this running with the tests for the 0.9 release.

**Comment by phlptp** [comment]
The QUICK_TEEST_ONLY flag has been added,  We need to test this and then  try it with the CI. 

Philip

**Comment by phlptp** [comment]
@nightlark  have you had a chance to test with this flag yet?

**Comment by nightlark** [comment]
It looks like the flag cuts the time to run the tests to ~1/3 with the ones that are currently enabled.

With/without QUICK_TESTS_ONLY time results (on LC):
core tests: 8.98 sec / 28.65 sec
application api tests: 28.35 sec / 108.30 sec
c api tests: 0 sec (not run)
player/recorder tests: 0.67 sec / 0.68 sec
Total time: 38.04 sec / 137.69 sec

**Comment by phlptp** [comment]
Can we close this issue?  Seems like the flag is working reasonably well?

**Comment by nightlark** [comment]
I'm trying it out on the appveyor build now. There's one build in the queue with it off, and another with it on.
