### ISSUE TITLE
C API message_t time floating point versus integer

### ISSUE THREAD

**Issue by jeffdaily** [GMLC-TDC/HELICS-src#168]
```
/home/username/HELICS/tests/helics/c_interface/FilterTests.cpp(193): error: in "filter_tests/message_filter_function_two_stage/_4": check m2.time == 2.5 has failed [2500000000 != 2.5]
```

The C API FilterTests.cpp specify the time delay filter using floating point.  When the message arrives, its time attribute is 2500000000 but the test is trying to compare it to 2.5.

**Comment by phlptp** [comment]
This one will be fixed in the next commit, working on a few others found during test execution
