### ISSUE TITLE
add caching for SWIG on Travis/appveyor

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/HELICS-src#178]
Given that the swig download seems to fail periodically, particularly when we are trying to get a release out.  SWIG should be cached so we are not dependent on the download site for all tests.

**Comment by phlptp** [comment]
@nightlark  is this completed?

**Comment by nightlark** [comment]
I think so. I'm waiting until the next commit to develop and tomorrow's cron job run to make sure the caches are updated. Also not sure that Appveyor's caching works -- we might need to host our own copy of the file.

**Comment by nightlark** [comment]
Caching is also working on Appveyor.
