### ISSUE TITLE
Copy helics.py to install folder on Linux and OSX

### ISSUE THREAD

**Issue by kdheepak** [GMLC-TDC/HELICS-src#185]

**Comment by kdheepak** [comment]
Currently the build system copies `src/swig/python/helics.py` but it should copy `build/swig/python/helics.py` to the install directory.

**Comment by phlptp** [comment]
shouldn't the copy location be dependent on whether SWIG was used or not?

**Comment by kdheepak** [comment]
Yes agreed.

**Comment by kdheepak** [comment]
Fixed in d20766c5e9dfbba14f8a7d159903bf5194b2758f and 057e5669f1f2b414b59aa1168577048ddc637c39.
