### ISSUE TITLE
Create a Jar file for the JAVA interface

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/HELICS-src#192]
The java files for HELICS should be packaged in a jar file for easy incorporation into java based projects.

**Comment by kdheepak** [comment]
And we can probably upload the jar file to the releases on github, to keep the repository from bloating.

**Comment by phlptp** [comment]
That is probably a good idea,  can we make jar files as part of cmake?  so that step gets done as part of the BUILD_JAVA option?  I have very little recent experience with JAVA so I don't really know how that might be done.

**Comment by phlptp** [comment]
By the time we get to the 1.0 release the github releases should potentially also have matlab binaries for windows/linux/mac and actual windows installers.

**Comment by phlptp** [comment]
Does anyone know when the java files would actually be created in the cmake process, is it during generation or do they not get generated until the project is built?

**Comment by phlptp** [comment]
It looks like CMAKE has some support for making jar files, but we might have to do that as a custom target that gets built when the SWIG project is built to create the *.java files

**Comment by phlptp** [comment]
included in #209
