### ISSUE TITLE
helics-config binary

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/HELICS-src#193]
It'd be great if we could have a helics-config binary be generated when someone builds/installs HELICS.

helics-config --includes could return -I/path/to/helics_install/include
helics-config --lib could return -L/path/to/helics_install/lib

**Comment by kdheepak** [comment]
I can tackle this.

**Comment by phlptp** [comment]
@kdheepak I made some modifications to the helics-config.  I think it should mostly work now.  Need to check with a package installer yet to make sure.
