### ISSUE TITLE
TOML for configuration

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/HELICS-src#194]
There will be some advantages to readability if 
[TOML](https://github.com/toml-lang/toml) could be used for configuration in place of or in addition to JSON.  

Toml is meant to be more human readable and includes comment support in the standard which JSON does not though the current JSON interpreter we use does support comments.

**Comment by bpalmintier** [comment]
I do like the idea of readability, but... Quick thought: JSON readers are now built into many language implementations and core libraries and seems to be here to stay long term.  Has TOML had a similar level of acceptance or would we be relying on libraries that might not be as well maintained long-term?

**Comment by phlptp** [comment]
I beleive this would be in addition to as opposed to a replacement for JSON.  The other option is YAML but the yaml libraries are a lot more complicated even if the files are more flexible.  There seems to be a number of different options for which library to use.
