### ISSUE TITLE
Add option to build boost with different toolsets

### ISSUE THREAD

**Issue by nightlark** [GMLC-TDC/HELICS-src#196]
Need a way to override the default toolset used to build boost.

**Comment by phlptp** [comment]
At one point I had some scripts in the scripts directory that built boost, looks like dheepak removed them for some reason.  But they were part of a set of scripts I am working on to build a whole bunch of different configurations and compilers.  The way I ended up building boost with the different compilers was actually remapping the compilers to the different ones for example mapping clang++ to clang++-4.0 along with all the other associated programs.  The same with GCC.  This does require sudo access.  The other option seemed to be writing some new configuration in bjam files, which I tried but could never get to work

**Comment by kdheepak** [comment]
Sorry about that! I saw they weren't being used and removed them. I probably misunderstood what they were for. I can add them back in if required.

**Comment by phlptp** [comment]
We can probably put them in a separate folder if would make things cleaner,  I use them as part of some scripts I was working on with google cloud to run a large number of different configurations, but I haven't put most of that into the repo yet.  but we do refer to some of those scripts in the documentation and presentations so it would probably be good to add them back in some fashion

**Comment by nightlark** [comment]
It's too bad they can't pick up and use what's in the CC and CXX vars like most other build systems.

**Comment by phlptp** [comment]
is it possible to just create gcc, g++, ld, etc symlinks in the local directory(or directory you call b2 in) that overrides the one in /usr/bin then you can just use with-toolset=XXXX
or the same with clang,  then you might not have to modify anything in the bjam files

**Comment by nightlark** [comment]
Symlinks might work. Or if needed, adding the directory with the symlinks to the start of PATH.

**Comment by nightlark** [comment]
I tried the symlink trick with two versions of gcc on LC, it also requires adding the directory with the symlink to PATH. On LC only the --with-toolset option needs changing, since the module loading of various compilers takes care of updating the system PATH already; Travis and other systems might need to create a symlink to make sure Boost uses the right version.
