### ISSUE TITLE
Add build to travis using clang 5.0 using --std=c++17

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/HELICS-src#201]
I think we should add a new build to travis that runs with the C++17 flags.  
This will require building boost with cpp17 flags and turning on some options in HELICS.

I want to make sure we work with the different settings and I think this is worth adding a new build to Travis.

**Comment by phlptp** [comment]
This will be dependent on #196

**Comment by nightlark** [comment]
Can it be added to the daily builds?
