### ISSUE TITLE
addLoadLibrary.cmake writes unsuitable library name

### ISSUE THREAD

**Issue by afisher1** [GMLC-TDC/HELICS-src#212]
In swig/java/addLoadLibrary.cmake the library that gets written inside of the System.loadLibrary() function when building the java bindings is "libJNIhelics".  System.loadLibrary("x") will attempt to look for libx.dll/so/dylib so when trying to run a java federate using the helics.jar  the System.loadLibrary("libJNIhelics") fails. Instead of "libJNIhelics" it needs to be "JNIhelics". Until this is fixed we can't use the jar file. Current work around is to edit the file and create the jar manually.

**Comment by phlptp** [comment]
is this still doing this after the merge from #210?  that was supposed to address this issue

**Comment by afisher1** [comment]
whoops! looks like this was addressed in 210 I'll doublecheck to confirm, sorry. Working from pull from yesterday.

**Comment by afisher1** [comment]
Yep 210 fixed this! Closing issue
