### ISSUE TITLE
add Java interface build to Appveyor

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/HELICS-src#220]
If I read the appveyor docs correctly they have a JDK installed.  So one thing we should do is enable the BUILD_JAVA_INTERFACE on Appveyor,  since we already build with Python.

**Comment by nightlark** [comment]
There aren't any tests yet for the Java interface, are there?

**Comment by kdheepak** [comment]
Not yet. I've added a Java example (that @HimanshuJain17 built and tested) to the examples folder. We can use this to perform testing.

**Comment by phlptp** [comment]
I think once #190 is completed we should be able to run those tests as part of the CI system.

**Comment by nightlark** [comment]
Building the Java interface on Travis also works. It doesn't add much to the overall build time.

**Comment by phlptp** [comment]
that is good,  did we have to install java in the environment or was it there already?

**Comment by nightlark** [comment]
It is already installed.

**Comment by phlptp** [comment]
Will we be able to run tests in java on travis easily or is that still going to be a challenge?

**Comment by nightlark** [comment]
It should be easy to run tests on Travis once we get them built.

**Comment by phlptp** [comment]
this issue was resolved in #225
