### ISSUE TITLE
Java SWIG string interface passed immutable string as input argument

### ISSUE THREAD

**Issue by kdheepak** [GMLC-TDC/HELICS-src#234]

**Comment by kdheepak** [comment]
This could potentially solve it.

```swig
// Add the following line to `swig/java/helicsJava.i`
%apply(char *STRING, int LENGTH) { (char *str, int maxlen) };
```

**Comment by kdheepak** [comment]
It looks like [this](https://github.com/GMLC-TDC/HELICS-src/blob/633223a/swig/helics.i#L18) is already there, but just needs to be altered slightly.

**Comment by kdheepak** [comment]
This SO answer is really useful as well for this - https://stackoverflow.com/a/11584600

**Comment by phlptp** [comment]
It seems like this is resolved for now, but we should revisit the API for the interfaces for HELICS 2.0
