### ISSUE TITLE
SWIG Python interface for strings can be named more appropriately

### ISSUE THREAD

**Issue by kdheepak** [GMLC-TDC/HELICS-src#235]
This [line](https://github.com/GMLC-TDC/HELICS-src/blob/e2ac53a/swig/python/helics.py#L1583) should change from

```python
def helicsSubscriptionGetString(sub, str):
    ...
```

to 

```python
def helicsSubscriptionGetString(sub, maxlen):
    ...
```

to be more accurate.

**Comment by phlptp** [comment]
how do we change the automatically generated file?

**Comment by kdheepak** [comment]
I'm not exactly sure, I was just hoping there was a way. Additionally, we should set `maxlen=100` by default if the user does not pass anything to this function.

**Comment by phlptp** [comment]
Do we have any idea how to do this yet?  If not I am going to place this issue on hold for the time being

**Comment by kdheepak** [comment]
I think we can close this, the typing information in Python helps address the original issue.
