### ISSUE TITLE
Move examples to separate repo

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/HELICS-src#247]
The examples in the HELICS repo should be moved to a separate repo to make them easier to test, and better demonstrate linking with helics and the execution of the HELICS runner.  we need to leave a couple for compilation tests in the helics repo but the majority should be moved to a separate repo to better separate concerns.

**Comment by phlptp** [comment]
@nightlark is this likely to be finished in 1.3(7/31/18)  or do we need to move to 1.3 first before it can be finished?

**Comment by nightlark** [comment]
I think we can remove the examples other than the ones as a test case today. The code in the examples repo is up to date and a copy of HELICS is getting installed on Travis -- I think the remaining step is writing a script to go through each C++ example and run cmake/make to build them, then start a small federation to test the examples.

**Comment by phlptp** [comment]
@nightlark Can you make a PR that does that.  And I will add some language to the ReadME that links to the examples Repo.    The examples repo will need a readme.md (can be brief but it needs something)
