### ISSUE TITLE
Fix travis warning for mac builds

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/HELICS-src#25]
Warning! PATH is not properly set up, '/Users/travis/.rvm/gems/ruby-2.0.0-p648/bin' is not at first place,
         usually this is caused by shell initialization files - check them for 'PATH=...' entries,
         it might also help to re-add RVM to your dotfiles: 'rvm get stable --auto-dotfiles',
         to fix temporarily in this shell session run: 'rvm use ruby-2.0.0-p648'.

We get this warning in the build log for the mac builds.  Probably should fix this at some point

**Comment by nightlark** [comment]
It seems to be related to ruby, which we aren't using, and it looks like it is happening before any of our build script runs.
