### ISSUE TITLE
Test suite for octave interface

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/HELICS-src#268]
The Octave interface needs a tests suite similar to whatever we come up with for the Matlab tests.  My assumption is we will be able to duplicate most of the code used in the matlab tests and just change a few things.  This issue should also be taken to imply that the octave interface is substantially equivalent to the matlab interface when used in code.

**Comment by phlptp** [comment]
#406  is the first step as now octave interface works on Linux

**Comment by nightlark** [comment]
The version of octave in the package repository used by Travis is 3.8; what's the minimum version we will support?

**Comment by phlptp** [comment]
I actually don't know.  The only ones I have tested on is 4.2 and 4.0.    It wouldn't surprise me if 3.8 works fine but it depends on SWIG.  Once we start adding the custom typedefs it might be a different story, or SWIG might have the generic wrappers that contain everything.

**Comment by phlptp** [comment]
the Swig documentation say its regularly tested on 3.8

**Comment by nightlark** [comment]
If it works with 3.8 then it will add some time to install octave, otherwise we may need to build octave from source which will take longer.

**Comment by phlptp** [comment]
Is there such a thing as a weekly cron job that is distinct from the daily ones that are already running?
If so that might be the place for octave

**Comment by nightlark** [comment]
There doesn't seem to be a way to distinguish the frequency of the cron job, only the branch it is run on. I think two ways of having a cron job similar to a weekly would be having octave/swig things in a separate repository, or having an outside service running that triggers a build on a regular schedule with some added information that tells it what kind of build to do.

**Comment by phlptp** [comment]
right now daily builds run off of develop correct?  
can we have a weekly run on master with some additional tests?

**Comment by nightlark** [comment]
Yes
