### ISSUE TITLE
Fix Python extension path issues on Mac and Linux

### ISSUE THREAD

**Issue by kdheepak** [GMLC-TDC/HELICS-src#273]
RPATH may also need to be fixed for when building the Python extension. Currently, users have to manually run the following for the Python extension to work.

```bash
export DYLD_LIBRARY_PATH=/path/to/helics_install/python/       # Mac
# OR
export LD_LIBRARY_PATH=/path/to/helics_install/python/         # Linux
export PYTHONPATH=/path/to/helics_install/python/
```

**Comment by phlptp** [comment]
@kdheepak  is this still an issue?

**Comment by kdheepak** [comment]
@phlptp This is still as issue. Essentially unless we add the Python extension (`_helics.so`) and the HELICS shared library (`helicsSharedLib.{dylib/so}` to the DYLD_LIBRARY_PATH or LD_LIBRARY_PATH, we are not able to use the Python extension. [These lines](https://github.com/GMLC-TDC/HELICS-src/blob/master/swig/python/CMakeLists.txt#L45-L46) are supposed to solve it but it doesn't seem to happen. It boils down to a `RPATH` issue.

![screen shot 2018-05-25 at 1 48 22 pm 3](https://user-images.githubusercontent.com/1813121/40563555-6a00a768-6022-11e8-9dab-348700258699.png)

The above screenshot is the Python error on `import helics as h`.  If I add `export DYLD_LIBRARY_PATH="/usr/local/Cellar/helics/1.0.2/python/:$DYLD_LIBRARY_PATH`, this works.

Alternatively, if I use `install_name_tool` to change the place that `_helics.so` looks for `libhelicsSharedLib.dylib`

```
install_name_tool -change @rpath/libhelicsSharedLib.dylib ./libhelicsSharedLib.dylib _helics.so
```

Then, everything works as long as you are in the same folder as the `libhelicsSharedLib.dylib`.

![screen shot 2018-05-25 at 1 55 55 pm 3](https://user-images.githubusercontent.com/1813121/40563813-6e111350-6023-11e8-86da-15e31985b4c3.png)

If I'm not in the same folder the above does not work.

**Comment by kdheepak** [comment]
I think the missing piece here is that when CMake builds the `_helics.so` Python extension, it is supposed to add a `-rpath` to the `libhelicsSharedLib.dylib`, which we are currently not doing / it is not working. Looking at the generated cmake files, it looks like it is currently only adding it to the `bin` directory.

```
    execute_process(COMMAND /usr/bin/install_name_tool
      -add_rpath "/Users/$USER/local/helics-clang-1.0.0/bin"
      "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/python/_helics.so")
```

**Comment by kdheepak** [comment]
Added the `lib` folder to the RPATH using CMake and that solved it on my Mac!
