### ISSUE TITLE
Core dump in python tests

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/HELICS-src#277]
One of the python tests is failing occasionally with a core dump.  We need to figure out the reason.
@kdheepak  does this ever happen on your system? and if so anychance you can provide some more insight into the exact locations of the error?  

```
../tests/python_helics/test_message_filter.py::test_message_filter_registration PASSED [ 33%]
../tests/python_helics/test_message_filter.py::test_message_filter_function /home/travis/.travis/job_stages: line 57: 12445 Aborted                 (core dumped) python3 -m pytest -v ../tests/python_helics
```

**Comment by kdheepak** [comment]
I ran this multiple times on my mac and it passes all the time.

<img width="1671" alt="screen shot 2018-04-23 at 2 43 14 pm" src="https://user-images.githubusercontent.com/1813121/39152191-bdb71324-4704-11e8-827e-4ec874097ad1.png">

Do the python tests fail with a core dump on Travis Mac VM alone or Linux VM as well?

**Comment by phlptp** [comment]
I am not sure I have ever seen it on the mac vm,  In Linux there seems to be two failure modes,  one is a core dump, the other just seems to hang.

**Comment by phlptp** [comment]
there seem to be two failure modes in the python tests right now, the seg fault as shown above, and a hang 
```
../tests/python_helics/test_value_federate.py::test_value_federate_initialize 
```
in the clang build.  
both are sporadic

**Comment by phlptp** [comment]
this isn't fully resolved, but it looks like it had to do with running the tests too close together and a new federate trying to attach to a closing broker.  which depending on the timing would either cause a hang or or an exception to be passed through, which caused a seg fault as we haven't caught all possible exceptions yet.    There seem to be a few other failure possibilities as well but those seem to be the main ones.  For the moment I have added a sleep after the registration tests, to give the system a little more time to close out the threads, before the next test starts.

**Comment by phlptp** [comment]
This hasn't been an issue in a while, so unless it crops up again in the next couple days I will close this issue.
