### ISSUE TITLE
Issues with Xcode 6.4 build

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/HELICS-src#278]
```
curl: (6) Could not resolve host: files.pythonhosted.org
Error: Failed to download resource "sphinx-doc--requests"
Download failed: https://files.pythonhosted.org/packages/b0/e1/eab4fc3752e3d240468a8c0b284607899d2fbfb236a56b7377a329aa8d09/requests-2.18.4.tar.gz
Error: python not installed
scripts/install-ci-dependencies.sh: line 155: pip3: command not found
```

**Comment by kdheepak** [comment]
We really should just use Miniconda3 on Travis, and create a Python2 conda environment if testing Py2 is required.

**Comment by phlptp** [comment]
I think we pretty much on the path to dropping all support for python 2, so I don't anticipate needing to test on python 2 or even wanting to test on Python 2

**Comment by phlptp** [comment]
This seems to have been resolved.  I will create a new issue if it comes up again.
