### ISSUE TITLE
C++98 Shared Library Test Fixtures vector problems

### ISSUE THREAD

**Issue by nightlark** [GMLC-TDC/HELICS-src#351]
The shared library tests using the C++98 interface give the following errors: `unknown location(0): fatal error: in "value_federate_tests2_cpp/test_block_send_receive/_0": memory access violation at address: 0xfffffffffffffff0: no mapping at fault address`

I've narrowed it down to any calls to the push_back method for the federates/brokers vectors in the struct. A minimal example would be replacing SetupTest with a call to push_back(nullptr) for either of those vectors. Adding a new vector called "brokens" with a type matching the brokers vector, then calling brokens.push_back(nullptr) in the SetupTest method works -- however if the instances of calling brokers.push_back in the the cpptestFixtures.cpp get replaced with brokens.push_back, the memory access violation error returns.

The bug doesn't seem to affect the ctest fixture, which uses vectors in a similar way.

**Comment by phlptp** [comment]
are you saying we are somehow pushing back nullptr onto the vector somehow.  If so that is probably the bug,  As that would mean the broker generation process failed somehow.  

Which I suppose explains why I have never seen that error on Windows.  Probably indicates one of the tests is not cleaning out properly before hand and they are colliding with the second failing in some fashion.

**Comment by nightlark** [comment]
Pushing anything (nullptr or not) onto the vectors that are part of the cpp shared library test fixture struct causes a segfault. I think it is a problem with the storage allocated for the vectors, not what is stored in them.

A minimal test fixture/case without Boost worked fine, so it could be something weird happening as a result of the boost test fixture macro.

**Comment by phlptp** [comment]
@nightlark  can you check if any of the recent updates made a difference toward this issue

**Comment by nightlark** [comment]
I'm still getting the same error with the changes from the develop branch.

**Comment by phlptp** [comment]
@nightlark  can you write a minimum test case that fails for you somewhere in the shared-library-tests-cpp?  I still don't think I totally follow what is happening here?

**Comment by nightlark** [comment]
I just tried the tests with the test_labels PR, the issue is fixed.

**Comment by phlptp** [comment]
I suppose that brings up an interesting question of what should the namespace on the C++98 wrappers be.  I made it helics98 but if we can't use helics:: then what should it be?
