### ISSUE TITLE
helicsSubscriptionGetString(...) slices the returned string by incorrect length

### ISSUE THREAD

**Issue by kdheepak** [GMLC-TDC/HELICS-src#365]
Tested in Python and MATLAB interfaces.

See discussion over at [Gitter on June 21, 2018 11:44 AM MST](https://gitter.im/GMLC-TDC/HELICS-src?at=5b2be411ad21887018d25cce) for more information.

**Comment by kdheepak** [comment]
This occurs when the publication data is a vector and the subscription is registered as a vector but retrieved as a string.

**Comment by phlptp** [comment]
PR #367
