### ISSUE TITLE
Occasional timeout in appveyor tests

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/HELICS-src#373]
There is an occasional timeout in the appveyor tests.  This should be investigated and fixed.
The first step will be turning on detailed output and running it a bunch of times to figure out which test is timing out.

**Comment by nightlark** [comment]
The fast_sender_tests in TimingTests.cpp times out, the check in the while loop on line 350 keeps passing until the timeout is reached.

**Comment by nightlark** [comment]
I added prints to show the currentTime and endTime, and ran the tests 36 times last night; none of the failed tests in that run were the fast_sender_tests in TimingTests.

3 of the failed tests the last line output before it timed out was `ErrorTests.cpp(174): Entering test case "duplicate_endpoint_names2"` (https://ci.appveyor.com/project/nightlark/helics-src/build/1.2.0.1767)
1 of the tests stopped in `ErrorTests.cpp(95): Entering test case "duplicate_publication_names2"` (https://ci.appveyor.com/project/nightlark/helics-src/build/1.2.0.1754)
1 of the times, it was a core test that failed with `IPCcore_tests.cpp(213): fatal error: in "IPCCore_tests/ipcComm_transmit_add_route": critical check counter.load () == 1 has failed [0 != 1]` (https://ci.appveyor.com/project/nightlark/helics-src/build/1.2.0.1747)

And there was one test with a weird compilation error for a line of code that compiled the other 35 times.

**Comment by phlptp** [comment]
@nightlark there was an erroreous "==" vs "=" in the fast_sender_tests  that may have been the source of the problem.  We might want to run a set of tests on develop to see if it recurs.

**Comment by phlptp** [comment]
@nightlark  can you start a series on appveyor to see if we fixed this issue?

**Comment by nightlark** [comment]
For 38 runs of tests on appveyor with the most recent release, all passed

**Comment by phlptp** [comment]
I think that would indicate this issue is solved.
