### ISSUE TITLE
Mac binary distribution

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/HELICS-src#379]
This should use the CPack stuff in cmake that is already setup
probably using the [DragNDrop](https://cmake.org/cmake/help/latest/module/CPackDMG.html) generator.

guessing a few generator specific fields will need to be added

though there might be some new generators as well if we were ok requiring a new cmake for the mac builds which isn't out of the question.  

This might be simple enough that it could be done and included with the 1.3 release.

**Comment by nightlark** [comment]
[CPackPackageMaker](https://cmake.org/cmake/help/v3.12/module/CPackPackageMaker.html) has been around since at least version 3.0 of CMake and can be used to create a component-based installer similar to Windows.

**Comment by phlptp** [comment]
That sounds like a good approach,  looks like there is only additional variable we would need to add.  Is PackageMaker something that is easily available(included) or something that would have to be downloaded?  @kdheepak  do you know much about it?

**Comment by kdheepak** [comment]
The main thing is that the dependencies are also coupled with the installation, i.e. boost and zmq libraries should be included. If CPackPackageMaker can do that that would be ideal. I've not looked into this much yet, but I'll start to. I have been doing a bunch of reading to find what needs to be done in general on a Mac. I'll post information I find on this thread.
