### ISSUE TITLE
Mac builds failing on develop and master

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/HELICS-src#381]
Looks like the mac builds are failing to build the java and python for some reason,  we probably should get this fixed.  

[failed job](https://travis-ci.org/GMLC-TDC/HELICS-src/jobs/399810674)

**Comment by nightlark** [comment]
I think the Java tests are failing because the Python wrapper isn't compiling, which happens before the Java tests are compiled.

**Comment by nightlark** [comment]
It's a homebrew issue.
