### ISSUE TITLE
MPI core development

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/HELICS-src#39]
We will need a MPI core and Broker to work on the HPC systems more directly than we can do currently.  
This and the TCP core will complete all currently planned cores.

**Comment by phlptp** [comment]
@nightlark How reasonably is it to have a prototype of the MPIComms object somewhat operational by Jan 15?

**Comment by nightlark** [comment]
A version using point-to-point MPI functions by Jan 15 should be possible, the one thing that could cause issues is matching send/receive calls.

**Comment by phlptp** [comment]
Can you elaborate a bit further on that issue?

**Comment by nightlark** [comment]
For the synchronous send/receive calls, every send needs a matching receive call. I think there is a similar constraint with the asynchronous send/receive calls.
