### ISSUE TITLE
ZMQ2 core type

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/HELICS-src#418]
Add a new communication core (ZMQ_2), that uses a single PUSH/PULL socket for cores and reduces use of REQ/REP sockets.  

This will alleviate the the possibility of running out of sockets if using a high number of federates on a single machine.    Basically copying the zmq core and adding in the necessary hooks so it is active.

**Comment by shwethanidd** [comment]
For some reason, running with helics runner results in huge number of sockets. Investigating that issue.
