### ISSUE TITLE
Design error object for shared libary

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/HELICS-src#422]
I think we want the signatures of the shared library calls to be switched around
```
output=helicsXXXX(helicsObject, other items, errorObject *eo)
```

this will clean up a lot of the language interface api functions substantially.

the question is what should the API around that object be
memory management,
accessors

It will have an error code
and a string describing the error

but how should this be accessed?

**Comment by phlptp** [comment]
Here is what I am proposing as an error api, and I would appreciate any feedback  or comments

define an error object as 
```
typedef struct helics_error
{
	int32_t error_code; /*!< an error code associated with the error*/
	const char *message; /*!< a message associated with the error*/
} helics_error;
```
the reasons for this are that the structure can be simply allocated on the stack when needed since it should only be 16 bytes.  This was preferable over an opaque object that would have required stack allocations, and it allows C users to directly access the underlying data.  

There are two functions that will be available for setting this up
```
/** return an initialized error object*/
helics_error helicsErrorInitialize();

/** clear an error object*/
void helicsErrorClear(helics_error *err);
```
these will return or initialize an error object (0 errorcode and the pointer pointing to an empty string).

All C API function that return can return an error code will have signature changed like
```
helics_status helicsFederateEnterInitializingMode (helics_federate fed);
```
will become
```
void helicsFederateEnterInitializingMode (helics_federate fed, helics_error *error);
```

this also allows the value return type of functions to be more natural
```
helics_status helicsInputGetInteger (helics_input ipt, int64_t *val);
```
becomes
```
int64_t helicsInputGetInteger (helics_input ipt, helics_error *error);
```
Also some functions like the creation functions can have the error return added to them whereas currently there is no means to get that information other than the return being NULL.

There are a few things to resolve yet that I don't have a clear answer yet. 
1.  the appropriate behavior if an error object is passed that already contains an error.  
 -  check and abort in every function
 - ignore it
 - check in a few functions it might matter or be possible

I am leaning towards the first option as that allows behavior to write a sequence of code and only check at the end knowing that if there was an early error nothing was done after that point, so would probably make the cleanest code.  
the second option has no performance penalty
The third is kind of a hybrid

2.   How should this behave in the different API's  
 - should the errorObject be wrapped up in the swig call and translated to an exception in the appropriate language API.    To my knowledge all current and proposed language API's have exceptions (Java, python, Matlab, octave, C#)  so it should be possible to hide the error object in all of the languages, have a check in the swig code and throw an exception if appropriate.  
- directly expose the errorObject

I think my preference would be the first since that simplifies the interface API's quite a bit, But I don't know what the expectations are for exceptions in these various languages, or exactly how to do this in the language API c interface.  

Comments welcome!

**Comment by trevorhardy** [comment]
We expect the broad user-base we're trying to attract to largely use simulators that have already been integrated into HELICS; most of them won't be dealing with these details. Anytime they are integrating a new simulator (or writing some small custom federate like a controller) they will have to dig into the details of HELICS. Which is to say, I don't know how much my opinion counts but....

I've never written against APIs that pass in an error object but this seems reasonable.

Regarding passed-in error objects that are not empty I would say option 1 (check and abort if not empty).

**Comment by phlptp** [comment]
Based on the comments and playing around with it, I think unless someone else has a really strong opinion and good rational, all functions will check and abort if the error object is not clear.

**Comment by kdheepak** [comment]
@phlptp Some of my comments are below.

I prefer the following behavior, as you mentioned

>  the appropriate behavior if an error object is passed that already contains an error.
>    - check and abort in every function (**_my preference_**)
>    - ignore it
>    - check in a few functions it might matter or be possible

With regards to the following:

> int64_t helicsInputGetInteger (helics_input ipt, helics_error *error);

What happens when the return type is more complex, like a subscription or publication object for example? Would it then also return the object or a pointer to the object?

Does the C API store references to all objects created? When the free library function is called, are all objects that were created free'd from memory? When a pointer to array of doubles is returned, whose job is it to free the memory corresponding to that array; the caller (user) or the callee (helics)? This could probably be done in the intermediate SWIG interface.

Have you seen other libraries that use this error pattern? I just want to make sure that we are not missing something. Every library I've found has only used the return error status pattern, and I'm just curious to see an example of a library that has used that you are recommended, just for reference. I'd be more confident in going down error input pattern route if I could study existing examples. If you can also share what you have prototyped with that would be great.

Alternatively, we can continue to use return C error status pattern (our current implementation) and just change the SWIG interface file to include the error checks and make the Python/MATLAB/Java functions behave similarly to what you are suggesting we do now.

Thoughts?

**Comment by phlptp** [comment]
Every function that returns a value will have some sort of return,  in cases of an error while creating an object, interface, or something else.  the value returned will be null.  And if the value is null, then there will be an error code, assuming you didn't give NULL to the error argument.   

This also allows us to give a more sensible error message in the case of registration failures, which should be helpful for diagnostics.  

The general concept was that the return values will either be some invalid marker (-1) for sizes,  null for the objects,  helics_time_invalid for times and doubles.  false for bool(since there are only two valid values.  

As far as memory management in the C interface.  all strings, vectors, and things like that are managed on the user side so there is no transfer.  

the publication, endpoints, filters, inputs are all linked to the federate so when the federate is freed all the interface objects are invalidated and the associated memory is released.  

For federates/cores/brokers the actual object used is a small wrapper.  This is freed when the free call is issued, but the underlying Helics object may stick around a while to manage closeout, or if it were cloned.  

queries and federateInfo objects are freed on the free call and no reference is maintained inside the library.  

The initial reason we went with the return code is that is typical C.  Libraries can get more advanced and use and errno(), and errstr() functions which is fairly common but these are global functions and in most implementation are not threadsafe, which is a hard requirement of HELICS.  So that would require a large amount of fairly heavy thread locks and mutexs to make work reasonably well and would not be intuitive.  

Some other notes on Memory management
the const char * pointers in message objects or from queries are valid until the next query using that object or the next message is obtained from the endpoint or directly from the federate.

The error handling  was mostly based on [this presentation](https://www.slideshare.net/StefanusDuToit/cpp-con-2014-hourglass-interfaces-for-c-apis)  that @kdheepak  pointed me to a while ago.  

a few modifications are that the helics_error is a concrete type from the C so we don't have to worry about allocation in the library.  The caller would just create one since it is only going to be at most 16 bytes for a 64 bit compiler.

**Comment by phlptp** [comment]
The way I see it, changing the error handling in the API does a few things
1).  gives us a way to return more error information (code+string)
2). does so in a way that avoids the global variables and threading issues of a errno, strerror type system.
3).  lets us add error returns to the registration and creation functions.  
4).  Makes the error handling much more obvious and upfront.  (ie)  if they aren't checked and cleared nothing further can happen if all functions abort.  if a null is used on the function, the error can be purposely ignored, but either way the user is supplying the operating mode.  
5).  This should make the language API's somewhat simpler and a little more intuitive on the return values.  

the cost is that the error pattern we are now using is not as commonly used, so may not be as intuitive to C programmers.  Also the cost is that there is an additional check at the beginning of each function, though I am doubtful this impacts performance in any meaningful way, and in many cases it also removes a few other checks, and eliminates a return value or input argument.

**Comment by abhyshr** [comment]
I like the idea of having an error object to give some sense of what the error is. Some thoughts/comments:
i) Typically, In C I've seen the status/error being returned as opposed to passed in as an input argument.  
```err = helicsXXX(helicsObject,other terms, outputobj *output)```
as opposed to
```output = helicsXXX(helicsObject,other terms, errobj *err)```
I don't have a strong preference for either form.
ii) There is a helics_status and now a new proposed helics_error. Would helics_status be removed? Would it make sense to combine them? Is their role different enough to still keep both of them?
iii) Would it make sense to also provide the error stack by the error object? I find it very useful for debugging to know which function on what line in which file caused the error.
iv) How much overhead would be there with this error object? Perhaps, it could be turned ON only for the debug build?

**Comment by phlptp** [comment]
Our initial design was based on typical C practice, so we returned a "helics_status" which was a typedef of an int basically an error code 0 if everything was fine some code from an enumeration otherwise.    The deficiencies in this were really shown in the language API's where an error code is not typical and it would be much more natural to just return values and throw exceptions instead of a return code, so the helics_error can be effectively hidden, which isn't true in the current form by returning a helics_status object.     

So helics_status is going away, but the same error_codes are present in the helics_error object which has an (integer) error_code fields.  and the helics_error also has a string message describing the error or providing some additional details on the source.  

I suppose a stack trace is possible but not sure it would mean much beyond the immediate call itself, so I am not sure it would be that valuable since any internal calls would by definition be opaque.  

The overhead on the typical function is two extra comparisons with 0,  one for a nullptr comparison, and one to check to make sure the error_code is 0 and otherwise abort.   Which judging from [compiler explorer](https://godbolt.org/z/upE2ph) is going to be 4 or 5 extra assembly instructions.    If there is an error, then there is additional overhead to fill the structure and manage the error, and probably trap the original exception.  

Given one of the main drivers is the language bindings,  since most of the time those will be run in release mode so I don't think enabling it only for debug would be that much use.

**Comment by bpalmintier** [comment]
Sounds like good progress. I definitely favor the goal of making the C interface structured such that it leads to more natural in the higher level languages based on it through SWIG (Python, MATLAB, etc.) even if it means a less common C development pattern.

**Comment by phlptp** [comment]
I think they should be identical for all but a few select functions.  Complex numbers being one example.  Matlab has native support, some other languages don't.  As far as the error objects, the different languages will throw different exceptions but the fact that they throw in the same circumstances should be identical.

**Comment by phlptp** [comment]
I am closing this issue after reviewing.  Any further issues with the error objects should be in a new issue.
