### ISSUE TITLE
Ease of use updates for C/SWIG interface

### ISSUE THREAD

**Issue by bpalmintier** [GMLC-TDC/HELICS-src#425]
Current configuration requires a few extra steeps that could be streamlined (some might propagate up to C++) for easier use. Initial suggestions:
1. Once a federate exists, it takes 3 functions to successfully get rid of it and in many cases to effectively exit the program (or get back to the command prompt in MATLAB, etc.). (terminate, free, and close library) Seems there could be a single function that does all of these and hence can easily be used to exit from error conditions, etc.
2. Must specify the number of federates at initialization. Seems this could default to 1 

Will post others as I work through some MATLAB (via SWIG) updates.

**Comment by phlptp** [comment]
Terminate is a call into HELICS to disconnect a federate from the federation.  It is still queriable and usable after this call.  All created subscriptions are still usable for instance to get the last data.  

In the C library, free will release the small wrapper around a federate.  It may or may not actually destroy the underlying federate Object depending on whether it was cloned or not.  

The closeLibary call destroys everything that has been instantiated thus far and shuts down all threads.  

These are all very distinct operations, and I am a little unclear what operations should be performed in various cases if you were to make a single call.    CloseLibrary will destroy everything and shut it down though that is kind of a blunt instrument.  

The 2.0 API is still open for enhancements so any suggestions are welcome.

**Comment by bpalmintier** [comment]
@phlptp I agree that these are different functionality and think we should certainly keep this fine grained control for advanced users/use cases, but in practice many federates will be standalone programs or otherwise have a simple configuration where all of these need to be performed during shut down. Having a unified function that does them all in this common sequence would make clean shutdowns and particularly multiple paths to shutdowns (such as on errors, etc.) much cleaner. See also the discussion on #429 for an example

**Comment by phlptp** [comment]
In the 2.0 release we will be moving to a single output API, with an error object, so I think that will be a little more intuitive for the interface API's, and get rid of the status output.

**Comment by phlptp** [comment]
The destroy function was added in #444, and will also be included in HELICS 2.0

**Comment by bpalmintier** [comment]
Great!
