### ISSUE TITLE
Julia language interface

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/HELICS-src#435]
* **I'm submitting a ...**
  - [x] feature request

### Feature Request 

Explore the use of  Julia interface.  Julia doesn't have a swig interface so we can't use the existing setup, but from what I have read it does have a pretty simple way to directly call C code so this would be writing a wrapper, similar to the python one.

**Comment by bpalmintier** [comment]
I’m definitely supportive and would like to volunteer to help with the example code generation. I wrote in my annual goals to learn some Julia, so this could be a good excuse... however, it would be great if someone else could lead getting the lower C calls to work.

**Comment by kdheepak** [comment]
See https://github.com/GMLC-TDC/HELICS.jl for the Julia interface. The tagged release for v0.1.0 is compatible with all the features that are tested in Python.

**Comment by kdheepak** [comment]
Closing.
