### ISSUE TITLE
Issue closing multiple message federates with unequal time requests

### ISSUE THREAD

**Issue by bpalmintier** [GMLC-TDC/HELICS-src#441]
* **I'm submitting a ...**
  - [x] bug

(Note: suggest adjusting the issue template so that the check boxes don't envoke a TODO list treatment in github.com summary review)

### Bug

* **What is the current behavior?**
If two message federates requested final times do not match, the federate with the latest time will hang forever (waiting for a blocking call to `helicsFederateRequestTime`, after the other federate has finished) forcing a hard shutdown.

* **What is the expected behavior? What is the motivation / use case for changing the behavior?**
This might be a more general concern, but at least for this situation, there either should be a way to either have a non-blocking call to request time, perhaps with some wall clock timeout value, or the ability for a message federate to be granted a time earlier than requested. Other solutions may be possibel 

* **What are the steps to reproduce this bug? Please provide a minimal working example of the bug if possible.**

Bug observed building the `knock-knock` Message federate example in MATLAB. See https://github.com/GMLC-TDC/HELICS-Examples/commit/b679c0431682f5bf887e5d538c637a2195be60f0

An easy way to reproduce this error is to change `their_response_delay` in `knock_knock.m` (near top of file, line 42) to `0.1` which will force non equal final time requests.

* **Please tell us about your environment:**

  - HELICS version: 1.3.0 (07-31-18)
  - MATLAB support, with a manual copy of `helicsDestroyFederate.m` and the revised version of `helicsStartup.m` from a recent version of `develop` (such as https://github.com/GMLC-TDC/HELICS-src/commit/b5fd8e32dc916331d039b09c40e586e315d10fc6) copied from `$HELICS_SRC/swig/matlab/` to `$HELICS_INSTALL/matlab`

  - Operating System: [all? tested under Mac]
  - Language Extension: [MATLAB]... may apply to all C library code, at least that with SWIG

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by phlptp** [comment]
let me make a test case about this in the C++ test case.  I am running into some possibly related issues in some things I am working on with the broker and core shutdown sequences.  

Just to be clear.  You are calling finalize the federate that you stop first?   and what core type were you using?
