### ISSUE TITLE
Preferred mode of indicating halt

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/HELICS-src#443]
What is the preferred mode of indicating a halt on a timeRequest call?
right now an error is thrown if the federation has terminated?

the other options is to simply return maxTime.  

This will apply to all languages with exceptions or an error return value.

**Comment by bpalmintier** [comment]
I think part of the challenge is that the current timeRequest call, as captured in the C library may not actually return, but rather seems to hang. Or is that just an artifact of the extra layer MATLAB imposes? see #441

**Comment by phlptp** [comment]
the timeRequest call is blocking, so it won't return until other federates allow it to do so based on time.  In certain circumstances if other federates crash, this can cause a hang at present.  We are slowly working through all avenues of this so it will become less of on issue as we deal with them.  But deadlocks are not really the issue this question is trying to address.

**Comment by trevorhardy** [comment]
@phlptp Can you help me understand what you mean by "a halt on a timeRequest call"?

**Comment by phlptp** [comment]
Basically an indication that the federation has stopped without error and no further time advancement or communication is possible.

**Comment by trevorhardy** [comment]
For FNCS I think federates asked for maxTime and once the broker saw that all were requesting maxTime (or the federation had been granted maxTime?) the broker sent a special message to indicate the co-simulation had completed and each federate wrapped up execution on its own. I can't recall us ever having a problem with this method (we more often had a problem with a federate dying unexpectedly like @bpalmintier was talking about) so I guess I'm in favor of something like this.

**Comment by phlptp** [comment]
the requestTime call will return a maxTime value when terminated, and the the iterative call will also return that time and the iteration_result portion will have the halted enumeration value.    I also tweaked it so there are a few less reasons to throw an error there and use the maxTime instead.

**Comment by phlptp** [comment]
Unless someone has further comments I will be closing this issue 9/11/18
