### ISSUE TITLE
Fix documentation links to the HELICS-examples repo

### ISSUE THREAD

**Issue by kdheepak** [GMLC-TDC/HELICS-src#446]
### Bug / Documentation

Some documentation links to the examples are broken. For example, see [lhere](https://gmlc-tdc.github.io/HELICS-src/introduction/hello-world.html) for links to [hello_world_sender.c](https://github.com/GMLC-TDC/HELICS-src/blob/master/examples/CInterface/hello_world_sender.c) and [hello_world_receiver.c](https://github.com/GMLC-TDC/HELICS-src/blob/master/examples/CInterface/hello_world_receiver.c).

**Comment by phlptp** [comment]
@kdheepak  is this something you can fix for 1.3.1?

**Comment by kdheepak** [comment]
I'll fix this tonight.
