### ISSUE TITLE
Add mac build to HELICS_2_0 branch

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/HELICS-src#447]
We need a Mac build enabled on the HELICS_2_0 branch.  
One of the mac builds probably 8 or 9 or later should be enabled on the HELICS_2_0 branch while it is in development to make sure it builds on that platform.    We don't need the full test yet, just one of the mac builds.

**Comment by nightlark** [comment]
There are build errors: https://travis-ci.org/GMLC-TDC/HELICS-src/jobs/425330646

**Comment by phlptp** [comment]
I think I fixed the build errors/other than the Java stuff.
