### ISSUE TITLE
remove xcode 6.4 support

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/HELICS-src#449]
[xcode 6.4 removal](https://travis-ci.org/GMLC-TDC/HELICS-src/jobs/425599734)
```
 Running builds with Xcode 6.4 in Travis CI is deprecated and will be removed in January 2019. If Xcode 6.4 is critical to your builds, please contact our support team at support@travis-ci.com to discuss options.
```

looks like travis will be removing support for Xcode 6.4.  
I think this means we remove the Xcode 6.4 travis build in the 2.1 release later this year.  Probably add a 9.X build for macs at the same time.   We are probably not changing the code level at that point, we will just drop the tested support, and anyone who uses it will have to report bugs if any compile errors show up.  

@nightlark  don't do anything with this until we are getting ready for a 2.1 release probably December.

**Comment by nightlark** [comment]
There's a 9.x build that I forgot to remove from a PR that was merged a few weeks ago -- I've been thinking of removing that one since we are triggering a lot of builds on each commit when a PR is open.

**Comment by nightlark** [comment]
It's around the time frame that xcode 6.4 support will be removed -- we should probably clean up the build matrix for XCode versions tested. Looking at the market share for the versions of macOS in the last 5 years and the age of hardware supported, it probably makes sense to target testing a XCode 9.x (macOS Sierra+) build for most commits, with testing of any older versions for PRs to master and/or develop.

**Comment by phlptp** [comment]
I would be ok with that.  If you want to tweak the build matrix for develop I think you can do so now.  Leave master as is until after the 2.0 final comes out next week.    I think it reasonable to run 1 newer mac build for each build and 1 or 2 older ones on the nightly build or on develop/master PR's

**Comment by phlptp** [comment]
@nightlark   what is the status of updating the build matrix to drop xcode 6.4.  It looks like some of the modules for HELICS 2.1 don't compile and I can't say I am all that inclined to fix them for a version unlikely to be used.

**Comment by nightlark** [comment]
I have a branch with it removed from the builds, and attempted switch to Xenial for the Linux builds that needs to get removed (undefined Boost functions during linking, maybe the wrong libraries getting found). I think the switch to Xenial images on Travis might wait until we start using Docker for the builds.
