### ISSUE TITLE
nonlings test failing occasionally

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/HELICS-src#456]
The nonlings test is failing occasionally with no output.

[travis](https://travis-ci.org/GMLC-TDC/HELICS-src/jobs/426727098)

I think it needs some output or other indication of why it is failing, and we should fix whatever it is that is failing.

**Comment by abhyshr** [comment]
Thanks. I'll take a look at it.

**Comment by abhyshr** [comment]
Btw, where are the HELICS C examples? I don't see them in $HELICS_SRC/examples.

**Comment by nightlark** [comment]
@abhyshr Most of the examples have moved to the GMLC-TDC/HELICS-Examples repository.
