### ISSUE TITLE
Clean CMake formatting

### ISSUE THREAD

**Issue by kdheepak** [GMLC-TDC/HELICS-src#46]

**Comment by kdheepak** [comment]
No good CMake autoformatter at the moment exists. We can revisit this issue when we find something that works.

**Comment by phlptp** [comment]
@kdheepak 
take a look at this
https://github.com/cheshirekow/cmake_format

potentially worth a shot

**Comment by kdheepak** [comment]
The author of the package suggested keeping an eye out for changes in cmake_format [1]. It currently may not work for what we need.

[1] https://github.com/cheshirekow/cmake_format/issues/2

**Comment by phlptp** [comment]
Do you know if it will work on some of the files like the folder specific ones a little further down the tree.  They are lot less complicated and could use some formatting as well even if the main one and some of the others won’t work yet.

**Comment by phlptp** [comment]
we should try this again, now that the cmake is cleaned up quite a bit from where it was.  It may work better now for quite a few of the files

**Comment by phlptp** [comment]
@kdheepak,  have you tried this recently?  If not might be worth trying again on some of the different cmake files

**Comment by phlptp** [comment]
@kdheepak , are you going to try running the formatter on the files in the config directory?

**Comment by phlptp** [comment]
We ran this on the remaining cmake files in PR #621
