### ISSUE TITLE
CMAKE option names

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/HELICS-src#465]
Just looking through the CMAKE stuff for HELICS 2.0 

We currently have some options 
MPI_ENABLE
ZeroMQ_ENABLE

but also ENABLE_PACKAGE_BUILD and ENABLE_CXX17 and a couple others

Wondering if MPI_ENABLE and ZeroMQ_ENABLE should be switched to ENABLE_MPI and ENABLE_ZeroMQ  for consistency and to put all the ENABLE options in the same place in any GUI.

**Comment by kdheepak** [comment]
I like this suggestion a lot!

**Comment by phlptp** [comment]
This has been changed in the 2.0 branch
