### ISSUE TITLE
change code coverage to 2.0 branch

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/HELICS-src#470]
@nightlark can you change the code coverage to be reporting on the 2.0 branch.    We will have to update this again in a month when we move 2.0 to master and develop but since I am adding tests to the 2.0 branch for the next while.  It would be very useful to see the coverage reports on that branch.

**Comment by nightlark** [comment]
Do you mean change the status button in the readme to be for the 2.0 branch? Code coverage builds are running for the 2.0 branch as part of the daily build, but the core test cases are timing out.

**Comment by phlptp** [comment]
Mostly I just want to see the code coverage results on the HELICS 2.0 branch.  At some point we will move over the status button, but that wasn't my concern for the moment.  I just will be writing some more tests over the next month and I want to track the coverage changes that result, and those will be on the 2.0 branch.  So I want to make sure we are getting coverage results from that branch into the webpage.  If the failure in the core-test branch was the reason,  I will look more into the issue there.

**Comment by nightlark** [comment]
Okay -- no output is the reason it is failing, but it could be that 10 minutes isn't enough to run all of the core tests on Travis; we can see if it passes on the daily build tonight.

**Comment by phlptp** [comment]
it looks like with coverage the tests are taking about double  normal time, and if the core_tests times out that would be 4 minutes with just that one.    I should figure out what is wrong with that test occasionally failing.  I need to enable some more detailed output to see which test is stalling.

**Comment by phlptp** [comment]
@nightlark  can you turn off the java and python builds for the coverage tests on the HELICS_2_0 branch?  They are not necessary for the code coverage purposes.  Actually come to think of it you can turn those off for the Valgrind, and Sanitizer runs as well.

**Comment by nightlark** [comment]
The Java/Python tests aren't running on the coverage/valgrind/sanitizer builds. Do we want the interfaces to not get built at all for these tests? And do we still want the README to have links to the codecov badge for the HELICS_2_0 branch?

**Comment by phlptp** [comment]
I don't think it is necessary to build the language interfaces since we build and test them for other tests.  For the README we plan to move the HELICS_2_0 to develop at the beta.2 release so it might not matter for long as the 2.0 branch will cease to exist in the near future.

**Comment by phlptp** [comment]
now that the 2.0 branch has migrated to develop this issue is closed
