### ISSUE TITLE
JSON configuration not standardized

### ISSUE THREAD

**Issue by trevorhardy** [GMLC-TDC/HELICS-src#475]
The current JSON configuration format does not define a specific method to map values across the HELICS/federate boundary. For example, if I need to publish a specific voltage out of GridDyn (say Voutput), there is no way from the configuration file to specify that the federate variable Voutput needs to map to the HELICS publication named "B123_V". Andy has set something up like this for GridLAB-D in absence of any existing standard (see below) but without this being supported by all simulators and a part of how we use the JSON configuration, usability is significantly impaired. Each simulator currently requires a different method of creating this mapping.

From "HELICS-Tutorial/test_system_data/gldFeeders/B2/G_1.DistributionSim_B2_G_1.json"
```
{
    "publications" : {
        "network_node" : {
            "distribution_load" : "totalLoad"
        }
    },
    "subscriptions" : {
        "network_node" : {
            "positive_sequence_voltage" : "TransmissionSim/B2Voltage"
        }
    },
    "endpoint_subscriptions" : {
        "Market_1" : {
            "fixed_price" : "fixed_price"
        }
    },
    "core_init_string" : "1"
}
```

**Comment by bpalmintier** [comment]
Agreed this is an important issue. @kdheepak has made some headway in a somewhat standardized approach with helics runner (now helics cli), but it does have some tool-specific pieces... and realistically it might need to. I’d say that the helics cli is likely a better starting point than the more limited and tool specific framework in GridLAB-D described above. In particular each tool's set of publications and subscriptions is captured in a simpler standardized way, while still allowing the flexibility to include tool-specific mappings. The current approach is to have this standardization at the helics-cli level and then include tool-specific plug-ins as needed to map the common format to the additional information that various tools might be needed. For example, the portion of a larger simulation.json file that corresponds to the same feeder looks like:

```
     "B2_G_1": {
        "endpoint_subscriptions": {
          "fixed_price": {
            "mapping": "Market_1/fixed_price",
            "type": "double"
          }
        },
        "folder": "test_system_data/gldFeeders/B2/G_1",
        "model": "DistributionSim_B2_G_1.glm",
        "publications": {
          "totalLoad": {
            "mapping": "network_node/distribution_load",
            "type": "complex"
          }
        },
        "subscriptions": {
          "TransmissionSim/B2Voltage": {
            "mapping": "network_node/positive_sequence_voltage",
            "type": "complex"
          }
        }
      },
```

The same info is there, but it is transferred around in a more generic way such that the subscriptions and publications are the dictionary keys, which can then be used in the same pattern for all federate types. The pieces within the corresponding sub-dictionary allow for the tool specific mapping that would for example change if you swapped out this feeder's simulation engine with say OpenDSS.

Taking a step back, I think a key missing piece is standardization of the subscription naming convention, since that is what other federates need to know to interface in a modular way. As described above, there may be a need for tool specific mapping of these standardized value/message names as part of the simulation configuration json, but having the publication and end points stay standardized would for example allow making changes only to the federate-specific config. 

This discussion also brings up the related note that there currently are three (or more) JSON config files each serving a different, but overlapping purpose: For HELICS there are lower-level federate configuration (although these options are also often set programmatically) and the higher-level simulation configuration used by helics-cli. Then a tool such as GridLAB-D may have its own JSON configuration separately. Things like subscription/publication lists may exist in all.

**Comment by phlptp** [comment]
This kind of thing is really what we need to be standardizing in the domain level interfaces.    At the application API level everything should universal and not try to do too much and not deal with anything implying stuff beyond a single federate.    At the domain API level is where we want to start to address things such as is discussed here, along with issues such as units, interface data types, and other conventions that might more relevant to one domain or another.

**Comment by trevorhardy** [comment]
The framework @bpalmintier  describes for helics_cli would work just fine and I have no problems with it. It is generic and fills the need. Would this require users to use helics_cli to have the convenience of JSON configuration for message passing? I'm OK with that as long as helics_cli is fantastic and everybody would want to use it anyway. (Which, after getting my first full demo of it last week, I think it is well on its way to being fantastic.)

@bpalmintier's comment about a naming convention is both inspiring and gives me an anxiety attack. Even simulators in the same domain make different modeling assumptions that makes it hard to imagine how we could establish something generic. How do we handle the fact that one simulator represents loads as a point ZIP load and the other represents loads as distributed along lengths of conductor? This is more than a naming convention problem that I don't know if we solve that simply. I'm very willing to be convinced.

**Comment by trevorhardy** [comment]
@phlptp, in trying to define a line between the application and domain APIs, does the current JSON config for a federate hold this line? If so, which side is it on?

**Comment by kdheepak** [comment]
@trevorhardy the JSON you've linked to is not what HELICS reads. It is the JSON that GridLAB-D reads. GridLAB-D reads that JSON and builds the federate using the C++ HELICS API. Does that answer your initial question?

**Comment by kdheepak** [comment]
cc @afisher1

**Comment by trevorhardy** [comment]
@kdheepak, thanks for clarifying that! Clearly I was confused based on my discussion with Andy yesterday. With that, I'm even more in favor of @bpalmintier's proposal as it incorporates it into an existing file rather than adding another configuration file. As a victim of multiple layers of configuration on other projects, I'm in favor of minimizing the file count as much as is reasonably possible.

**Comment by phlptp** [comment]
the HELICS json/toml is really just a wrapper around the Application API,  there is nothing in there that is not part of the application API, so it clearly is entirely in the application API layer.

**Comment by phlptp** [comment]
That was one of the drivers of defining inputs in HELICS 2.0, so if no knowledge of the federation was available you can still define all the interfaces.    I think it is appropriate if available,  I thought forcing it was inappropriate, hence the development of inputs which don't require such knowledge.

**Comment by phlptp** [comment]
Part of the design of HELICS was to impose as low an integration overhead on federates as possible.   I  really don't want to back off of that by imposing that the various tools read a HELICS defined file format of some kind.  That strikes me as a bad idea and a large disincentive for usage of HELICS.   I think if we even wanted to consider that we would have to have some very well thought out API's that made that as low of overhead as possible.  And we would still then have the issue that most major modeling tools would then have at least two files to deal with, one to define the simulation and one to define the HELICS connections.  I know in the case of GridDyn HELICS is an add on so nothing in the core of GridDyn is even aware of HELICS, that is all dealt with in the individual models and an add on coordinator. 

I am all in favor of coming up with a set of standard naming conventions and interface patterns for particular domains, I think that fits perfectly fine in the layered approach HELICS has taken.  

As far as overall simulation configuration, maybe we have our own JSON format that is tailored to our use, but if we want to go down that route we should also fully support some of the existing/developing standards like [MAP-SSP](https://fmi-standard.org/related/)

**Comment by trevorhardy** [comment]
@phlptp, we can discuss this in depth in the meeting we'll be having next week but here is my argument in a nutshell: usability is greatly enhanced by standardization. Having a standardized format that all simulators that are used to build HELICS co-simulations makes the job of setting up the co-simulation much easier. Integration is a one-of exercise but running a co-simulation using those simulators will happen much more often.

If we have a well-defined federate configuration file format, we, the HELICS team, can have a function/method that reads in that format and handles most of the configuration. This doesn't have to be a large burden on those integrating a new simulator; that function/method would do the work and there would be a small amount of simulator specific configuration that the integrator would have to handle. Jacob and I here at PNNL have been discussing it and we'll show the team our proposal next week.

@bpalmintier, the file format Jacob and I are proposing would not handle the construction of the co-simulation *a la* helics_cli. Jacob and I are in favor of not duplicating information and would like to find a way for the configuration via helics_cli and the individual federate configuration JSONs to inform each other.

**Comment by phlptp** [comment]
One of the key use cases is an ability to very quickly create a small control federate, that could easily be a one off and should be able to be done very quickly,  so mandating that this type of federate be configurable through a file is NON-STARTER.  Any such thing must be opt-in and part of domain or higher level API wrappers.  

You can probably rig something up as prototype that meets the needs of your current application and is definitely worth exploring.  We can talk more next week but to make something like this broadly applicable and work well is going to take an enormous effort, and it isn't clear that we should be doing that vs making use of one of the existing  standards that do similar things and tie into Dheepaks notion of application plug-ins.  

The Cyder project had some notion of a JSON connection file as well, so the concept is interesting.

**Comment by trevorhardy** [comment]
Looping in this discussion thread from a call between myself, @phlptp, @kdheepak, @eberleim, and @jacobhansens, we've decided that a new metadata field in the existing JSON configuration file named "info" will be supported by HELICS. This field will contain simulator-specific information of an arbitrary nature that HELICS will store after parsing the publication, subscription, and endpoint objects in the configuration JSON and return when queried by a federate. The content of the "info" field can be structured in any way in the configuration file (simple quoted string, JSON, XML, CSV, etc) and when queried, HELICS will return the the contents of this field as a string and leave it up to the federate to parse it appropriately. There is no requirement that the formatting of this field will be standardized across simulators.

The intended application of this data is to support the mapping of data received by the federate from HELICS into its own internal data structure. Due to the arbitrary nature of the data in the field, though, there isn't any reason that it couldn't be designed for other purposes by the integrator of a given simulator.

@phlptp and @eberleim will be working to implement the necessary changes and will provide updates in this thread as those have been completed, tested, and integrated into the existing C/C++ codebase.

**Comment by phlptp** [comment]
My current thinking on this is to add a single field in the BasicHandleInfo structure, which is common to all interfaces,  this would put it at the core layer,  which I suppose isn't necessary but the alternative at the Application API layer is to basically replicate the interface for each of the interface types.    Putting it at the core layer also means it could apply to filters universally which don't have to be created through a federate.    The info field would not be part of the constructor,  But would be set or accessed through 2 core.hpp functions.  setInterfaceInfo(handle, const std::string &info),  const std::string &getInterfaceInfo(handle).  There would need to be corresponding functions in the Application API classes that called this for the individual types and objects, and the appropriate readers in the file parsers.  

This would also mean the brokers would have an extra field to store some metadata about interfaces if the need were to arise in the future.

**Comment by phlptp** [comment]
PR #514  resolves this issue
