### ISSUE TITLE
Update to the main ReadMe file

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/HELICS-src#478]
This issue is to capture dialog and discussion pertaining to updating the readme file for the main page in preparation for an eventual 2.0 release.   

Some current suggestions 

We use the idea of examples twice, ones in Getting started (external repo) and also in Documentation. Is the documentation referring to old embedded repo folders? If so let's delete, if not perhaps we can find a new name?
Add mention of the HELICS book documentation effort?
Need to refresh the tool list. Guessing there are some additions, and I think GridLAB-D may now be part of the main release.
For the tools, might we need some form of version-based table? at least for 1.3.1 vs 2.0?

**Comment by nightlark** [comment]
- Update ns-3 HELICS module link in the README
- Recommend newer CMake version than minimum, esp when using the C++14 interface (3.5 has a bug that can make find_package not work on some systems; fixed by 3.8)
