### ISSUE TITLE
ns-3 build failure

### ISSUE THREAD

**Issue by trevorhardy** [GMLC-TDC/HELICS-src#483]
**Describe the bug**
When building ns-3 with HELICS integration the build fails to build the helics-filter-application

**To Reproduce**
Attempt to build ns-3 with HELICS integration

**Environment (please complete the following information):**
 - Operating System: Mac OS X 10.12.6
 - Language Extension: python 2.7.10
 - Compiler: Apple LLVM version 8.0.0 (clang-800.0.42.1)
 - HELICS version: 1.3.1 (09-23-18)
 - ZMQ version: 4.2.5
 - Boost version: 1.67.0
 -  

**Additional context and information**

**configure command**: ./waf configure --prefix=/Users/hard312/testbeds/HELICS_testbed --enable-examples --with-helics=/usr/local/ --boost-includes=/usr/local/include --boost-libs=/usr/local/lib --with-zmq=/usr/local/ --python=/usr/bin/python

**configure output**:Setting top to                           : /Users/hard312/source/HELICS-ns-3-dev-git 
Setting out to                           : /Users/hard312/source/HELICS-ns-3-dev-git/build 
Checking for 'clang' (C compiler)        : /usr/bin/clang 
Checking for cc version                  : 8.0.0 
Checking for 'clang++' (C++ compiler)    : /usr/bin/clang++ 
Checking for compilation flag -std=c++11 support : ok 
Checking for program 'python'                    : /usr/bin/python 
Checking for python version                      : (2, 7, 10, 'final', 0) 
python-config                                    : /usr/bin/python-config 
Asking python-config for pyembed '--cflags --libs --ldflags' flags : yes 
Testing pyembed configuration                                      : yes 
Asking python-config for pyext '--cflags --libs --ldflags' flags   : yes 
Testing pyext configuration                                        : yes 
Checking for compilation flag -Wno-array-bounds support            : ok 
Checking for pybindgen location                                    : not found 
Checking for python module 'pybindgen'                             : not found 
pybindgen missing => no python bindings
Checking boost includes                                            : 1_67 
Checking boost libs                                                : ok 
Checking for boost linkage                                         : ok 
Checking for click location                                        : not found 
Checking for program 'pkg-config'                                  : /usr/local/bin/pkg-config 
Checking for 'gtk+-2.0' >= 2.12                                    : not found 
Checking for 'libxml-2.0' >= 2.7                                   : yes 
Checking for type uint128_t                                        : not found 
Checking for type __uint128_t                                      : yes 
Checking high precision implementation                             : 128-bit integer (default) 
Checking for header stdint.h                                       : yes 
Checking for header inttypes.h                                     : yes 
Checking for header sys/inttypes.h                                 : not found 
Checking for header sys/types.h                                    : yes 
Checking for header sys/stat.h                                     : yes 
Checking for header dirent.h                                       : yes 
Checking for header stdlib.h                                       : yes 
Checking for header signal.h                                       : yes 
Checking for header pthread.h                                      : yes 
Checking for header stdint.h                                       : yes 
Checking for header inttypes.h                                     : yes 
Checking for header sys/inttypes.h                                 : not found 
Checking for library rt                                            : not found 
Checking for header sys/ioctl.h                                    : yes 
Checking for header net/if.h                                       : yes 
Checking for header net/ethernet.h                                 : yes 
Checking for header linux/if_tun.h                                 : not found 
Checking for header netpacket/packet.h                             : not found 
Checking for NSC location                                          : not found 
Checking for OpenFlow location                                     : not found 
Checking for 'sqlite3'                                             : yes 
Checking for header linux/if_tun.h                                 : not found 
Checking boost includes                                            : 1_67 
Checking boost libs                                                : ok 
Checking for boost linkage                                         : ok 
Checking for libzmq.so location                                    : /usr/local/ (given) 
Checking for HELICS location                                       : /usr/local/ (given) 
Checking for library zmq                                           : yes 
Checking for library helics-static                                 : yes 
['-O0', '-ggdb', '-g3', '-Wall', '-Werror', '-Wno-unused-local-typedefs', '-Wno-potentially-evaluated-expression', '-std=c++14']
Checking for program 'sudo'                                        : /usr/bin/sudo 
Checking for program 'valgrind'                                    : /usr/local/bin/valgrind 
Checking for 'gsl'                                                 : yes 
python-config                                                      : not found 
Checking for program 'doxygen'                                     : not found 
---- Summary of optional NS-3 features:
Build profile                 : debug
Build directory               : 
BRITE Integration             : not enabled (BRITE not enabled (see option --with-brite))
DES Metrics event collection  : not enabled (defaults to disabled)
Emulation FdNetDevice         : not enabled (needs netpacket/packet.h)
Examples                      : enabled
File descriptor NetDevice     : enabled
GNU Scientific Library (GSL)  : enabled
Gcrypt library                : not enabled (libgcrypt not found: you can use libgcrypt-config to find its location.)
GtkConfigStore                : not enabled (library 'gtk+-2.0 >= 2.12' not found)
HELICS Integration            : enabled
MPI Support                   : not enabled (option --enable-mpi not selected)
NS-3 Click Integration        : not enabled (nsclick not enabled (see option --with-nsclick))
NS-3 OpenFlow Integration     : not enabled (OpenFlow not enabled (see option --with-openflow))
Network Simulation Cradle     : not enabled (NSC not found (see option --with-nsc))
PlanetLab FdNetDevice         : not enabled (PlanetLab operating system not detected (see option --force-planetlab))
PyViz visualizer              : not enabled (Python Bindings are needed but not enabled)
Python Bindings               : not enabled (PyBindGen missing)
Real Time Simulator           : not enabled (librt is not available)
SQlite stats data output      : enabled
Tap Bridge                    : not enabled (<linux/if_tun.h> include not detected)
Tap FdNetDevice               : not enabled (needs linux/if_tun.h)
Tests                         : not enabled (defaults to disabled)
Threading Primitives          : enabled
Use sudo to set suid bit      : not enabled (option --enable-sudo not selected)
XmlIo                         : enabled
ZMQ Integration               : enabled
'configure' finished successfully (3.062s)

**build error message**: In file included from ../contrib/helics/model/helics-filter-application.cc:5:
./ns3/log.h:486:12: error: call to function 'operator<<' that is neither visible in the template definition nor found by argument-dependent lookup
      m_os << param;
           ^
../contrib/helics/model/helics-filter-application.cc:71:47: note: in instantiation of function template specialization 'ns3::ParameterLogger::operator<<<helics::Message>' requested here
  NS_LOG_FUNCTION (this << id.value() << time << *message);
                                              ^
./ns3/helics.h:15:15: note: 'operator<<' should be declared prior to the call site or in namespace 'helics'
std::ostream& operator << (std::ostream& stream, const helics::Message &message);
              ^
1 error generated.

Waf: Leaving directory `/Users/hard312/source/HELICS-ns-3-dev-git/build'
Build failed
 -> task in 'ns3-helics' failed (exit status 1): 
	{task 4519280088: cxx helics-filter-application.cc -> helics-filter-application.cc.1.o}
['/usr/bin/clang++', '-O0', '-ggdb', '-g3', '-Wall', '-Werror', '-Wno-unused-local-typedefs', '-Wno-potentially-evaluated-expression', '-std=c++14', '-fPIC', '-I.', '-I..', '-I/usr/local/Cellar/gsl/2.5/include', '-I/usr/local/include', '-I/usr/local/include/helics', '-DNS3_BUILD_PROFILE_DEBUG', '-DNS3_ASSERT_ENABLE', '-DNS3_LOG_ENABLE', '-DHAVE_SYS_IOCTL_H=1', '-DHAVE_IF_NETS_H=1', '-DHAVE_NET_ETHERNET_H=1', '-DHAVE_GSL=1', '-DHAVE_SQLITE3=1', '-DNS3_HELICS', '-DHAVE_ZMQ', '../contrib/helics/model/helics-filter-application.cc', '-c', '-o', '/Users/hard312/source/HELICS-ns-3-dev-git/build/contrib/helics/model/helics-filter-application.cc.1.o']

**Comment by trevorhardy** [comment]
Closing issue and moving to the ns-3 repo where I should have posted it.

**Comment by kdheepak** [comment]
Opened issue is here: https://github.com/GMLC-TDC/HELICS-src/issues/483

**Comment by kdheepak** [comment]
Opened issue is here: https://github.com/GMLC-TDC/ns-3-dev-git/issues/10
