### ISSUE TITLE
Python API doesn't support TOML

### ISSUE THREAD

**Issue by trevorhardy** [GMLC-TDC/HELICS-src#487]
**Describe the bug**
C/C++ supports parsing TOML files as a HELICS function, Python (and perhaps other bindings) 

**What is the expected behavior?**
All supported language bindings support parsing both JSON and TOML.

**Comment by phlptp** [comment]
The function `helicsCreateXXXXFromJSON` will actual read TOML files just fine.  This has been fixed in 2.0 but hasn't been renamed in 1.X.X to maintain compatibility.  

The 1.3.2 adds a `helicsFederateRegisterInterface(fed, file)`  this will read json or toml.

**Comment by trevorhardy** [comment]
Ah, so not a problem after all (other than the naming).
