### ISSUE TITLE
HELICS defines for log levels conflict with other libraries

### ISSUE THREAD

**Issue by nightlark** [GMLC-TDC/HELICS-src#488]
**Describe the bug**
Some of the log levels defined in flag-definitions.h conflict with the names and values defined for log levels used in other libraries (ie ns-3).

**Environment (please complete the following information):**
 - Operating System: all
 - Language Extension: C, C++ (shared library)
 - HELICS version: develop (10-16-18)

One option for avoiding these naming conflicts would be prefixing all of our defined flags in headers with "HELICS_", which is more verbose but seems to be common among other libraries. Any other options or thoughts for dealing with conflicting defines?

**Comment by phlptp** [comment]
Is this on the 2.0 branch?  In 2.0 should be be an easy fix since we haven't locked down the API yet,  A little more annoying in the 1.X branches since we need to keep API compatibility.  
Which defines specifically are conflicting?

**Comment by phlptp** [comment]
what does "ux" label mean?

**Comment by nightlark** [comment]
UX is user experience/useability.
