### ISSUE TITLE
C interface should be tolerant of nullptr for optional arguments

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/HELICS-src#49]
optional arguments that are listed as const char * in the C interface should be tolerant of nullptr or NULL as an argument.

**Comment by phlptp** [comment]
@HimanshuJain17 can you check some of your test cases with nullptr inputs instead of "" to make sure that nullptr actually works now as well and if it does work close out this issue.

**Comment by HimanshuJain17** [comment]
@phlptp These functions are working:
`helicsCreateBroker`

These are not working with the `nullptr`:

`helicsRegisterPublication`

`helicsRegisterGlobalPublication`

**Comment by phlptp** [comment]
What fields were you putting as nullptr?

**Comment by HimanshuJain17** [comment]
`type` and `units`

**Comment by phlptp** [comment]
@HimanshuJain17  I just added an update to hopefully fix the issues with the nullptr type in RegisterPublication

**Comment by HimanshuJain17** [comment]
@phlptp Thanks.

**Comment by phlptp** [comment]
I think this is fixed, if someone finds another issue related to sending nullptrs,  please open a new issue as a bug.
