### ISSUE TITLE
no pytest on XCode 7.3 macOS 10.11 travis build

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/HELICS-src#490]
**Describe the bug**
the travis builds for xcode 7.3 are failing python tests
11/17 Test #17: python_value_federate_test .......***Failed    0.04 sec
/usr/local/bin/python3: No module named pytest

**What is the expected behavior?**
looks like some issue with travis modules,  either disable the python tests in that build or install the module.  

[link](https://travis-ci.org/GMLC-TDC/HELICS-src/jobs/442533579)

**Comment by phlptp** [comment]
@kdheepak This does not appear to have fixed the issue.  Did I merge before you had finished?

**Comment by nightlark** [comment]
I'm not sure what's happening. I've encountered issues with getting tests running on LC with the right way of calling pip/pip3 to work with python3, but part of that might have been due to the module system for loading different versions of python.

**Comment by nightlark** [comment]
@kdheepak unless you've found something getting pytest working, I'm leaning towards disabling the python tests on the Travis mac builds

**Comment by nightlark** [comment]
Fixed by PR #541
