### ISSUE TITLE
HELICS python support doesn't play well with Anaconda

### ISSUE THREAD

**Issue by trevorhardy** [GMLC-TDC/HELICS-src#495]
**Describe the bug**
Verification of HELICS support in Python fails after following the installation instructions at https://gmlc-tdc.github.io/HELICS-src/installation/mac.html on the Mac. I'm assuming this is because my (@trevorhardy) Python installation is managed by Anaconda which does not use `PTYHONPATH` to find modules (maybe?)

Specifically, when verifying the Python support using iPython the `import helics` command throws an error: 

```
In [1]: import helics
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-30959e25f87e> in <module>()
----> 1 import helics
```

**What is the expected behavior?**
`import helics` would not throw and error in iPython

**To Reproduce**
Follow the installation guide for Macs at https://gmlc-tdc.github.io/HELICS-src/installation/mac.html.

**Environment (please complete the following information):**
 - Operating System: Mac 10.12.6
 - Compilier: clang-800.0.42.1
 - HELICS version: 1.3.2 (10-20-18)
- iPython info: Python 3.6.0 |Anaconda custom (64-bit)| (default, Dec 23 2016, 13:19:00)

**Comment by kdheepak** [comment]
Did you add the following line your .bashrc?

```
export PYTHONPATH=/Users/$(whoami)/local/helics-1.3.1/python:$PYTHONPATH
```

You might need to change the line above to point to the right location.

**Comment by kdheepak** [comment]
Are you using `brew` to install HELICS?

**Comment by kdheepak** [comment]
I have only been using it with Anaconda/Miniconda on my Mac, so that's not the issue. This is probably a PYTHONPATH / PATH / DYLD_LIBRARY_PATH issue. If you can paste the full traceback that would be helpful.

**Comment by trevorhardy** [comment]
I added the appropriate line to my .bashrc but forgot to `source` it in the terminal window I was testing. 100% user error, and re-testing in iPython worked as the installation guide indicated.

**Comment by kdheepak** [comment]
Great!
