### ISSUE TITLE
Fully document a couple examples

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/HELICS-src#50]
Should have a couple examples fully documented and easy to use
I am thinking the messageFed, and valueFed and piSender and piReceiver

basically more completely documenting the code and also linking a web page in the documentation that highlights them.  

and some easy scripts to run them.

**Comment by kdheepak** [comment]
I think [this](https://gmlc-tdc.github.io/HELICS-src/introduction/hello-world.html) partially addresses this PR. We will need more examples that specifically explain different concepts.
