### ISSUE TITLE
Blocking on finalize call

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/HELICS-src#531]
This relates to issues #441, and a few other issues.

One issue is that I have not had much success in replicating these issues, and I have possible explanation as to why.    My best guess is that it has to do with the program termination sequence.  I do most of my testing on Windows and in the unit test code.  In the unit test code there is no program termination so everything completes normally.  On windows and in the C++ API, threads are allowed to shutdown normally as well, also no issues as far as I can tell.    But on mac's and Linux when using the shared library  things are a little different.  Right after finalize which kicks off a series of events that lead to everything being shut down.  Often the program ends.  Depending on the OS and kernel this can immediately lead to the library being shutdown,  and the threads generated by the library being shutdown hard with none of the usual closeout stuff.  For the program in question this usually isn't a problem.  But with networking stuff in HELICS, if it hasn't had a chance to actually send the disconnect message then it could case a "deadlock",  I am slowly working towards timeouts on the federate links but that would only cover up the actual issue in this case.  

The only solution to this I can come up with right now is changing the finalize() calls to be a blocking call.  This would block the finalize call until it has been acknowledged by the higher layer.    This would be significant change to HELICS in adding a blocking call.  But I think it might resolve some of these issues that have been cropping up, that have been impossible to replicate in the testing code.  So I am seeking opinions on this, as it would need to be in place for 2.0 since it would be an API change.

**Comment by phlptp** [comment]
Also likely related to #527, #456, #296, and #392.

**Comment by Jacobhansens** [comment]
I support changing finalize() to be a blocking call. I see no downside of making it blocking and I have been having a lot of sporadic issues related to less than clean exits from federates. 

I would suggest that we spin off a ticket and give it a try. Specifically I would be interested in seeing if it solves the issue of #527 that I looked at yesterday. I think it might.

**Comment by phlptp** [comment]
The  downside is increased complexity in the termination sequencing in the internal code.  and the federate could block for some time so it will slow down things.  It will also probably slow down the test code though not sure how much.    

I suspect you are right that a number of the sporadic issues are due to the disconnect process particularly in regard to shared library.

**Comment by trevorhardy** [comment]
@phlptp, how would the blocking once a federate had completed all its contributions to the co-simulation slow things down? I think I'm missing something.

Also, is the main concern with increased complexity the possible introduction of bugs and further problems down the road? If so, do we anticipate it is worse than the current state where we aren't able to reproduce the problems @Jacobhansens is seeing? In other words, if overall we have the same number of bugs but after making this change the bugs are now reproducible, I would consider that a step forward. 

Said differently, do we have other alternatives to solving this problem?

**Comment by phlptp** [comment]
The federate will now have to wait for acknowledgement,  which will involve at minimum a round trip communication to next higher level of broker, and depending on the layout possibly a series of them.    It also means that more care will need to be taken if you have more than one federate running in the same thread.  (admittedly this is more of an issue with the test code than seems to be the case in actual usage).  

I am hopeful this will solve some of the issues, perhaps most of the ones that deal with federation close out.  But  I suspect some of the ones related to socket closing will not be impacted and may be exaggerated.

**Comment by trevorhardy** [comment]
@phlptp, ahh that makes sense that it will add some more data on the bus. This won't be a significant increase in traffic will it, though, given how much data is exchanged during even simple co-simulations.

 And I can see how multi-federate simulators will be tricky.
