### ISSUE TITLE
SWIG command produce warning for cmake 3.10

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/HELICS-src#54]
Looks like the version check in the python CMake files doesn't work for cmake 3.10, it produces a bunch of warnings on deprecated SWIG commands.

**Comment by phlptp** [comment]
I need to verify this on on a system with cmake 3.10 and swig yet but I think that should fix it, once I verify I will   close the issue.

**Comment by kdheepak** [comment]
I'm able to confirm that it works now with 3.10.
