### ISSUE TITLE
getInputType() function returns empty string even though type is specified in the configuration file

### ISSUE THREAD

**Issue by Jacobhansens** [GMLC-TDC/HELICS-src#551]
**Describe the bug**

getInputType() function returns empty string even though type is specified in the configuration file for that specific input.

**What is the expected behavior?**

getInputType() should return the type specified for the input in the configuration file

**To Reproduce**

Call getInputType() from federate that configures inputs from a configuration file.

**Environment (please complete the following information):**
Ubuntu 16.04
HELICS 2.0 Beta 2

**Additional context and information**

**Comment by Jacobhansens** [comment]
I did something wrong in my setup. I can confirm this is not a bug and that the getInputType() does indeed work in HELICS 2.0 beta 2.

**Comment by Jacobhansens** [comment]
Opening again as @phlptp let me know he has test cases where something is wrong.

**Comment by phlptp** [comment]
For the C and language API's   there is helicsInputGetType  and helicsInputGetPublicationType(),   do we think this is clear enough?

**Comment by Jacobhansens** [comment]
@phlptp, did you make a decision with respect to the C and language API's? I think my original issue is solved in this one but want to make sure you agree before closing.

**Comment by phlptp** [comment]
I pretty much left it as is, since the C API is based on the interface objects functions, not purely on the Federate and Core Objects, so the change was limited to some internal changes.  And Filters in the C api don't support defined types so there is no function for them.    At this point I am inclined to leave it be.

**Comment by Jacobhansens** [comment]
We will leave it as is then. closing out this issue
