### ISSUE TITLE
application_api_ci_test not running completely

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/HELICS-src#563]
**Describe the bug**
I don't think all the ci test are being run in travis.    I ran the tests locally and discovered some failures from a recent commit that should have been caught by the CI test execution specifically in the application_api_ci_tests  and it is running a bit faster than I would expect,  this needs to be checked somehow not sure how though.

**Comment by nightlark** [comment]
Was there a pattern to the test cases that failed?

The command it is running is: `application-api-tests --run_test=@ci --log_level=test_suite --report_level=short`; do the expected tests run?

**Comment by phlptp** [comment]
That is what I am trying to figure out,  when I run that command it runs 802 tests,  I seriously doubt they are running on travis that many tests in that amount of time, and I have no idea why they are not all running.

**Comment by nightlark** [comment]
How many tests does it run when you leave out the —run_test=@ci? I’m getting 163 with, and 838 without, using boost 1.66; maybe issues with labels in a particular version of boost, or cross-platform bug?

**Comment by phlptp** [comment]
I get 1488 without and 802 with.  On windows

**Comment by phlptp** [comment]
boost 1.68 and 1.69 produce the same results,  I don't have any other versions on my system right now

**Comment by nightlark** [comment]
Here's a verbose log of the test cases entered to compare against Windows: https://travis-ci.org/GMLC-TDC/HELICS-src/jobs/470838459

**Comment by phlptp** [comment]
If I had to guess it looks like it is skipping all the tests based on core_types and its variants.

**Comment by phlptp** [comment]
just looking at value_federate_key_tests  the ones that are running are the non data test cases, and the data test cases based on something in that file, like lists of files

**Comment by nightlark** [comment]
I think it is using some of them, since it seems to have tests that are run multiple times (_1, _2, _3...)

It would be nice if they listed the data value used instead of an index.

**Comment by nightlark** [comment]
Oh so it’s the lists of cores defined in the test fixtures aren’t working?

**Comment by phlptp** [comment]
All the data test cases I looked at in the application_api_tests were run from data that was local to the file,  So it doesn't seem to be data test cases in generate that aren't working.  And the core ones seem to be working just fine in the shared library tests

**Comment by phlptp** [comment]
yeah, all the ones that don't seem to running use the lists of cores

**Comment by nightlark** [comment]
The main difference that stands out is the application api test fixture defines the vectors using macros; it could be a difference in how the compilers are handling macros.

**Comment by phlptp** [comment]
it works on msys compilers, but that might not mean much same results as MSVC

**Comment by phlptp** [comment]
Ok, I tried converting all the lists to constexpr const char *[]  that seemed to work,  unfortunately now we have several errors, some are easy to fix others could take some time to work through, and are possibly ones that have been around a while.
