### ISSUE TITLE
custom command line parser

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/HELICS-src#565]
Currently we use boost::program_options for command line parsing.  This is a powerful library that handles many of the features HELICS depends on for parsing arguments in a sane fashion.  

The main drawback is that it is a separately linked library as part of Boost that seems particularly susceptible to linking issues.    So the question is should we replace it to simplify  the build process.  
If longer term we replace the use of boost::asio with the asio library we may be able to completely get rid of any need to any boost libraries and just use the header only versions.  

But the argument processing is central piece so we need to go down that road.  

I have looked through several different libraries and one main limitation with most is an ability to ignore unused arguments.  Since the arguments in helics are processed in a cascading way this is a critical feature.  

If we were to design our own a few features that I think would simplify things

- allow multiple arguments (short and long form) to mean the same thing [NOT in BOOST]
- allow case insensitive matching for long form arguments [NOT in BOOST]
- allow stripping of '_'  for long form arguments [NOT in BOOST]
- include string processing, i.e all arguments are in a single string vs argc  and *argv[] [NOT in BOOST]
- allow processing of argument in `vector<string`> [NOT in BOOST]
- cascading processing with objects  (this would allow us to actually check if arguments are unused in the entire cascade  which is impossible now) [NOT in BOOST]
- some form of file processing probably toml
- support windows form options
- allow positional arguments
- support for flag, int, double, string, and `vector<string>` type arguments
- support --no-*  or --disable-*  for disabling long form flag arguments

**Comment by trevorhardy** [comment]
Since this is an implementation detail and not my area of expertise, take my comments with a grain of salt.

I'm generally in favor of increasing the likelihood of a successful build. Everybody hates dependency problems and one less dependency that can be flaky is a good thing.

That said, it seems like command line argument parsing should be a very solved problem and though I don't doubt that @phlptp did a good job looking around at options, it is baffling to me that we can't find an existing solution to support the features we'd like to have.

I also don't have any sense of how long it would take to make a highly reliable version of our own command line parser. This seems like the kind of thing that could take a while to really iron out well. It may be better in the long run to work around the limitations of a reliable parser rather than half-reinvent the wheel at great cost (relatively speaking). 

Said differently, (not being a developer and hopefully never really having to work directly with any of this), I'm pretty sure I'd rather spend the time and effort on increasing usability in other ways (documentation, bug fixes, etc...). This is not a feature I'm personally super interested in (which doesn't mean it isn't something the project should do).

**Comment by eberleim** [comment]
It's worth considering adopting an existing (acceptably licensed) open source header-only package that has most of these features, and making the modifications we need and contributing them back. My concern is the similar to @trevorhardy 's here, that creating a new CLI is basically adding one more component we're wholly responsible for, and will probably be a time-consuming and expensive process. 

After a quick look around I found a header-only package which could be linked as a submodule and built as a cmake add_subdirectory, and has most of the things on that list, so I feel like we'd definitely be re-creating the wheel here. Only unknown for me is what license we need for HELICS to link in another project. 

https://github.com/CLIUtils/CLI11 for reference.

**Comment by phlptp** [comment]
That one is probably closer than some of the others, at least after the 1.7 release comes out.  Not sure how challenging it would be to add some of the missing features.  I poked at cxxopts for a while, but there was enough missing from it that I am not sure it would be worth it to try to get in place and functional for our purposes.  

I guess a couple questions are whether windows options matter,  we currently support them,  does anyone thing losing that support will be problematic.

**Comment by nightlark** [comment]
CLI11 is also the one that I was looking at, and it seems pretty close:
- allow multiple arguments (short and long form) to mean the same thing
- allow case insensitive matching for long form arguments
- cascading processing with objects (this would allow us to actually check if arguments are unused in the entire cascade which is impossible now) [could be possible using subcommands with some changes to the arguments taken]
- some form of file processing probably toml [has something like INI file]
- allow positional arguments
- support for flag, int, double, string, and vector<string> type arguments [I think t supports all or most of those]

Based on trying out the windows style options, they don't seem to be completely functional -- I don't think anyone could be depending on them right now.

**Comment by bpalmintier** [comment]
Agree with the thought of not re-inventing the wheel on this one (or having to keep in round). I'm actually quite surprised this capability doesn't exist in the C++ STL, beyond getopt.  Thoughts on options:
* I first thought--wait don't we already have to deal with boost, many links seem to point to it as a powerful option. But Seem @phlptp described well the exciting option of possibly moving away from the need to to compile boost which would be a fantastic build process simplification.
* CLI11 does sound promising
* Some additional options are compared in: https://attractivechaos.wordpress.com/2018/08/31/a-survey-of-argument-parsing-libraries-in-c-c/
* There is also a nice table of comparisons in the README for https://github.com/CLIUtils/CLI11

**Comment by phlptp** [comment]
There is no way we are going to be able to get rid of boost and for the test framework I don't see us moving away from the unit_test_framework.  so that will need to be linked.    But after discussion with Ryan it might be possible to change the main HELICS library to not require compiled boost libraries.    Boost 1.69 changes the system library to be header only but we are a long time away from requiring boost 1.69,  but asio as a standalone is another possibility that is what boost::asio is built from to begin with.  That leaves program_options as the boost library which as far as I can tell is the best/most powerful program options library.  The reasons we chose it are that we are already using boost and it filled our needs for command line processing, and we have long since adapted to some of the short comings.  

But it is the library that has given us the most linking problems on different platforms.  And remains the most complicated C++ library we link to. (other than the std lib)  The other libraries  libzmq are linked through C interfaces.  So if we are to consider working towards a simpler linking process program-options is the linchpin and by far the most work.  So that leaves us considering alternatives.  Once you get beyond the simple libraries there isn't that many options.  Add in the features we rely on  namely the help printing, positional,  type checking, allowing unused,  and fully crossplatform  it rapidly dwindles 

Apart from the custom solution  cxxopts and CLI11 are probably the two that might be worth considering.  I did a hard look at cxxopts and am not sure how much work it would be to add the missing required features vs writing our own that does exactly what we need.    CLI11 has fewer missing features and looks a little easier to modify but it is a pretty big difference in how it is used vs cxxopts which would have required very little modifications to HELICS.   

Maybe the best approach will be to take CLI11 modify it  for some of the features then write a wrapper to use in HELICS that does some of the other things we need.

**Comment by phlptp** [comment]
I think a reasonable target would be 2.2  certainly nothing is going to happen in the next few months.  But if it is worth moving in this direction it will take some time to understand and implement.  And that means now is the time for the discussion, and we can try it out in other projects and see what issues we might run into and that sort of thing, with CLI11 I could probably move the stuff in helics_fmi to that pretty quickly,  that doesn't have the layers that helics does so should be pretty simple and that will give us some insight to see about the practicality for HELICS.      Based on past experience the longer lead time we have on some things of this nature the less work it actually is, so good discussion

**Comment by phlptp** [comment]
I think this was completed with #662
