### ISSUE TITLE
Add a get function for an Endpoint's default destination.

### ISSUE THREAD

**Issue by afisher1** [GMLC-TDC/HELICS-src#569]
* **I'm submitting a ...**
  - [ ] bug
  - [x] feature request
  - [ ] support question

### Feature Request / Support Question

Currently the application api does not provide a getter function for an Endpoint's target destination. I propose the following function be added to the Endpoint class.

const std::string &getDestination(void);

The function should return the target destination. If the target destination was not defined then the function should return an empty string.

**Comment by nightlark** [comment]
Addressed by PR #570
