### ISSUE TITLE
Broker connection time out hard coded in ZMQ core

### ISSUE THREAD

**Issue by Jacobhansens** [GMLC-TDC/HELICS-src#578]
**Describe the bug**

Large federations can fail with the error `zmq broker connection timed out (2)` because the time out of the zmq polling is set to a fixed value and proper mechanism for retry is not in place. I have consistent failures at 1000 federates each with 100 publications on a single machine. 

With local source code changes to retry connection I am able to run the large federations without any issues.

**What is the expected behavior?**

I would suggest that the user is able to set this time out value to ensure the value is sensible for the size of the federation. We already have a timeout property of the core initialization and that might be a good option to use this value.  

**Environment (please complete the following information):**

Ubuntu 16.04
Helics 2.0 beta 2

**Comment by phlptp** [comment]
Can you PR the changes you made for the retry?  I will take a look at the timeout

**Comment by Jacobhansens** [comment]
I think the current knobs you describe are sufficient. I think they provide enough flexibility while not overloading the user with options to set. I would suggest as part of this we check all timeouts in each core to make sure they all map to one of these user specified options. I would furthermore suggest the following couple of things as improvements:

- Make sure the documentation that @trevorhardy is working on fully covers how each of these work and in what cases the user should be modifying them.  
- Either add more descriptive warning and error messages or create a portion of the documentation that includes more description for each and potential solutions to avoid them

**Comment by phlptp** [comment]
leaving this open while we check the other comms and for documentation issues for the next week.
