### ISSUE TITLE
Code coverage build is failing

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/HELICS-src#603]
**Describe the bug**
the code coverage build on [travis](https://travis-ci.org/GMLC-TDC/HELICS-src/jobs/481240273) is failing 
**What is the expected behavior?**
 it should pass

**Additional context and information**

as best as I can tell it is getting killed by travis.  Not entirely clear why.  We should have this build passing to get accurate coverage numbers.

**Comment by nightlark** [comment]
The exit code is 137 is `kill -9` on the travis_wait command. One of the Travis CI staff* said that it is most likely running out of memory on the host, so I think it is outside of our control beyond changes to the tests we are running. Previous and subsequent code coverage cron jobs look like they ran without issues.

*https://github.com/travis-ci/travis-ci/issues/4192#issuecomment-119053081
