### ISSUE TITLE
Boost extraction

### ISSUE THREAD

**Issue by nightlark** [GMLC-TDC/HELICS-src#605]
Issue for tracking the changes that would be needed to remove the transitive dependency on Boost currently required of projects using HELICS.

- [x] Replace `program_options` in `common/argParser.h` with an alternative for parsing arguments (ex: https://github.com/CLIUtils/CLI11)
- [x] Replace Boost `asio` with the upstream `asio` library (https://think-async.com/Asio/) -- removes dependency on Boost `system` without using any undocumented defines. `common/AsioServiceManagerFwd.hpp` should then be possible to remove
- [x] Remove use of `filesystem` from `application_api/FederateInfo.cpp`, and `common/argParser.h` to break the transitive dependency. Also used in `apps/helicsApp.cpp`, `apps/helicsConfigMain.cpp`, `apps/Player.cpp`, `apps/Recorder.cpp`, and `apps/Tracer.cpp` -- removal would allow people compiling HELICS that don't care about the tests to skip the build step for Boost
- [x] Extra: check for Boost headers included by public API headers -- removing would make so user projects don't need to find any parts of Boost (ValueConverter_impl.hpp uses boost::iostreams; this isn't part of the public API and involves serialization using cereal, which is C++ only and won't work with other languages. If a user chooses to use it for serialization, they need to include their own copy of boost includes)

**Comment by phlptp** [comment]
does federateInfo use boost filesystem other than in argParser?  

If we wanted to remove it the applications,  what is a replacement for boost::filesystem?  short of C++17 filesystem I presume we don't need to remove it from the test system,  that uses the boost test and I have no desire to try to replace that.  

for std::filesystem we would need gcc 8.0 or clang 7.0 as a minimum version.

**Comment by nightlark** [comment]
It looks like federateInfo doesn't use boost filesystem outside of the argParser.

Based on the way we're using it, the functions provided by https://github.com/wjakob/filesystem would be pretty close to a drop in replacement (the Mac situation with C++17 filesystem is a mess -- seems to be the inspiration for the headers). PlatformSTL seems to be another alternative.

Anyway, for most users getting a copy of Boost libraries shouldn't be a big deal. It might save some small hassle for people that need copies of HELICS built with different compilers.

**Comment by phlptp** [comment]
For the test system the main thing is checking if files exist and some of removing files and paths, Also the getting the temp directory.

**Comment by phlptp** [comment]
One issue Is for dealing with the single thread cores/federates and comms.  I am considering using boost::fiber.  There would be an option to disable all these cores.  But I believe that boost::fiber is dependent on boost::context which is not a header only library and I don't think there is an alternative.  There are of course ways to design it without boost::fiber, but the advantage with boost fiber is that there is only minimal code differences between using the fiber library and threading so most of the code is pretty similar or can be made so with some tweaks so can be built pretty quickly.  If we don't use boost::fiber I am not sure what the alternative is without a pretty big rewrite and much longer time frame.

**Comment by nightlark** [comment]
PR #662 replaces `boost::program_options` with `CLI11` and removes use of `boost::filesystem` from the application api.

**Comment by nightlark** [comment]
PR #664 removes the dependency on the Boost Filesystem library.

**Comment by phlptp** [comment]
@nightlark  can this be closed?  or is there any more steps to complete

**Comment by nightlark** [comment]
Yes, it looks like this is done!
