### ISSUE TITLE
Testing of python interface

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/HELICS-src#62]
Need some way to automatically test the python interface.  If the python interface gets built we should have some means of testing that

- [x] it built properly
- [x] it linked and loaded properly
- [x] it can execute without error

this would probably be through a few test cases running in travis and ideally appveyor.  as well as some more extensive tests we can do in a nightly build.

**Comment by kdheepak** [comment]
We probably don't need a separate issue for this if #102 includes examples in Python.
