### ISSUE TITLE
Automated documentation update

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/HELICS-src#624]
**Describe the solution you'd like**
Have Travis or some other CD automatically build and upload the documentation on commits to master

**Comment by nightlark** [comment]
GitHub Actions could be a good fit for this when it comes out.

**Comment by nightlark** [comment]
Revisiting using ReadTheDocs might be worth looking into -- apparently they have Doxygen installed on their build servers, and their support for switching between documentation for different versions is likely to be less error prone and effort to maintain than what we have.

**Comment by kdheepak** [comment]
It'll definitely solve our multiple versions issue.

**Comment by kdheepak** [comment]
We can close this: https://helics.readthedocs.io/en/latest/
