### ISSUE TITLE
Remove space in Windows installer's default location 

### ISSUE THREAD

**Issue by kdheepak** [GMLC-TDC/HELICS-src#627]
Currently the windows installer's default location is `C:\local\Helics v2.0.0-rc1`. We should make it `C:\local\helics-v2.0.0` going forward.

**Comment by phlptp** [comment]
It keys off the version number and build so once the -rc1 is removed that should automatically change.  But  we should fix that space.  

On my machine the default ends up being C:\local\helics_2_0_0-rc1   or are you talking about the installer itself rather than the Install build?

**Comment by phlptp** [comment]
This is fixed in #621 by adding a folder parameters to CPACK_NSIS variable
