### ISSUE TITLE
Timing-demo errors in HELICS 2.0

### ISSUE THREAD

**Issue by vchinde** [GMLC-TDC/HELICS-src#633]
I have installed HELICS 2.0 and while running timing-demo example I run into the following errors. I did changes to the timing-demo example based on pysender/pyrecevier example.
![fed2](https://user-images.githubusercontent.com/38356140/53433508-c1819380-39b1-11e9-8299-18c25b2ea6a2.PNG)
![fed1](https://user-images.githubusercontent.com/38356140/53433510-c21a2a00-39b1-11e9-9e5f-8ef50e838093.PNG)

Attached are the code for the timing-demo example

[timing_federate1.txt](https://github.com/GMLC-TDC/HELICS-src/files/2906743/timing_federate1.txt)
[timing_federate2.txt](https://github.com/GMLC-TDC/HELICS-src/files/2906744/timing_federate2.txt)

**Comment by kdheepak** [comment]
I'm guessing there's an existing broker running. Can you try restarting your terminal or your computer? Can you confirm that you get the same error when you run it the first time after you restart your computer?

**Comment by vchinde** [comment]
I restarted my computer and observe the same error

**Comment by kdheepak** [comment]
in timing_federate1.py

```
    initstring = "-f 2" # line 45
    ...
    def create_value_federate(broker, deltat=1.0, fedinitstring="--federates=1"): # line 55
```

<img width="1680" alt="screen shot 2019-02-26 at 1 26 03 pm" src="https://user-images.githubusercontent.com/1813121/53443952-20eb9d80-39ca-11e9-9f4e-c0a5ee90b92a.png">

I see that you are trying to convert v1.3.x to v2.0.0 code. I had to make a few more changes to get it all to work in v2.0.0. I'll let you attempt the same before I share my version here. Let me know if you have more questions.

**Comment by vchinde** [comment]
Thanks for the suggestion. I did made it to work.

**Comment by kdheepak** [comment]
Great! If you like, you can submit a PR with your changes and we'll merge your contribution.
