### ISSUE TITLE
Mac OS X build instructions

### ISSUE THREAD

**Issue by temcdrm** [GMLC-TDC/HELICS-src#641]
**Describe the bug**
Failed to complete a HELICS build on Mac OS X 10.13.6 with gcc 7.3 and Python3 support by following the directions on RTD. The main problems were:

- Cmake looked for SWIG, and I gave up trying to build SWIG and its dependency, PCRE
- Make couldn't find Boost symbols for the x86_64 architecture, even though otool showed those to be present in the Boost libraries

**Additional context and information**
The following changes worked for me:

- Send -DENABLE_SWIG=OFF to Cmake.  The documentation suggests -DDISABLE_SWIG=ON (https://helics.readthedocs.io/en/latest/installation/language.html#helics-with-matlab) but that doesn't seem to work.  Please correct, and also add here: https://helics.readthedocs.io/en/latest/installation/mac.html#building-helics-using-gcc-and-python
- The documentation says Cmake >= 3.4 is required, and I already had 3.6.1, but apparently Cmake >= 3.8 is required to properly detect Boost 1.64. Cmake 3.14 is currently the latest version. Please instruct the user to "brew upgrade cmake" or download from cmake.org, if they already have Cmake installed.
- To finally build and test Boost, these instructions are what worked for me, substituting gcc 7.3 for 8.1: https://solarianprogrammer.com/2018/08/07/compiling-boost-gcc-clang-macos/
- To finally build and test HELICS, this is what worked for me: `cmake -DCMAKE_INSTALL_PREFIX="/Users/mcde601/local/helics-gcc-2.0.0/" -DBOOST_ROOT="/usr/local/boost-gcc-1.64" -DBUILD_PYTHON_INTERFACE=ON -DENABLE_SWIG=OFF -DUSE_BOOST_STATIC_LIBS=ON -DCMAKE_C_COMPILER=/usr/local/bin/gcc-7 -DCMAKE_CXX_COMPILER=/usr/local/bin/g++-7 ../` followed by `make clean; make -j 4; make install`

**Comment by kdheepak** [comment]
Thanks for the detailed instructions. We'll update the documentation.

**Comment by kdheepak** [comment]
For reference, this is the command I use to build HELICS:

```
cmake -DBUILD_PYTHON_INTERFACE=ON -DCMAKE_INSTALL_PREFIX="/Users/$USER/local/helics-gcc-2.0.0/" -DBOOST_ROOT="/Users/$USER/local/boost-gcc-1.69.0" -DCMAKE_C_COMPILER=/usr/local/Cellar/gcc/8.2.0/bin/gcc-8 -DCMAKE_CXX_COMPILER=/usr/local/Cellar/gcc/8.2.0/bin/g++-8 -DZMQ_USE_STATIC_LIBRARY=ON -DUSE_BOOST_STATIC_LIBS=ON ../
```
