### ISSUE TITLE
Test Matlab interface

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/HELICS-src#65]
Need some way to automatically test the Matlab interface.  Given it uses Matlab and a custom version of swig this may not be workable in the automated tests, but we should be able to set something up in a nightly build test.  

- [x] it built properly
- [x] it linked and loaded properly
- [x] it can execute simulations without error

**Comment by kdheepak** [comment]
It appears that the way to run MATLAB tests on Travis is to use Octave to run the tests.

**Comment by phlptp** [comment]
The pi_sender and pi_receiver work so I think this is done
