### ISSUE TITLE
helicsInputIsUpdated is reset when sending as a double and receiving as a string

### ISSUE THREAD

**Issue by kdheepak** [GMLC-TDC/HELICS-src#655]

**Comment by phlptp** [comment]
@kdheepak  can you test this again with the develop branch.  I think I fixed it but I want to make sure it got fixed with what you doing.

**Comment by kdheepak** [comment]
I will check and get back to you.

**Comment by phlptp** [comment]
@kdheepak  any update?

**Comment by phlptp** [comment]
@kdheepak  have you had a chance to test the fixes yet?

**Comment by kdheepak** [comment]
I have not unfortunately, I'll get to it this afternoon.

**Comment by phlptp** [comment]
@kdheepak have you tested this yet?

**Comment by kdheepak** [comment]
I've tested this on the latest develop and this is resolved.
