### ISSUE TITLE
specification for remote connections is cumbersome and complicated

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/HELICS-src#71]
The specification of remote connections to brokers and other objects needs to be a little less complicated

as an example
```
./messageFed --name="fed1" --target="fed2" --coreinit="--broker_address=\"tcp://10.254.21.101\"" --local_interface=\"tcp://10.254.21.86\""
```

ideally something like this would probably be better 
```
./messageFed --name="fed1" --target="fed2" --broker="tcp://10.254.21.101"
```

with the local_interface being inferred from as either external or internal based on the broker specified

the broker had to be specified like
```
2 --local_interface="tcp://10.254.21.101"
```

This is also an interesting question of whether the broker should by default open up external ports or not.

**Comment by phlptp** [comment]
I think we need a few other people to test this out

**Comment by phlptp** [comment]
@kdheepak maybe we can work on this later this afternoon.  I think I made some improvements but it could probably be better yet.  This also may have to be continued through the beta release

**Comment by kdheepak** [comment]
That sounds great!
