### ISSUE TITLE
Update README/install instructions with minimum dependencies

### ISSUE THREAD

**Issue by kdheepak** [GMLC-TDC/HELICS-src#82]
Currently Boost is listed 1.58, should be changed to 1.61

**Comment by phlptp** [comment]
To be clear, the HELICS library itself requires 1.58
the Test systems and few other components requires 1.61.    I have built it with 1.58 recently

**Comment by kdheepak** [comment]
Thanks for the clarification, and that's what I had assumed as well. But @JianhuaZhang3 and I tried this on Ubuntu and it gave us cmake errors. We can check again.

**Comment by phlptp** [comment]
I was able to build it (without test cases) on Lubuntu (on a pentium M single core)  with 512 MB of RAM with boost 1.58,  so it does work,  spits out a warning message about the tests which we may want to remove if testing is turned off, but it does compile
