### ISSUE TITLE
Intermittent failure in message filter tests 

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/HELICS-src#85]
```
C:/projects/helics-src/tests/helics/application_api/test-filters.cpp(106): fatal error: in "filter_tests/message_filter_function/_1": critical check mFed->hasMessage (p2) has failed
3: Failure occurred in a following context:
3:     core_type = ipc_2;
```

This failure likely has to do with timing between filters and multiple cores.  It only shows up occasionally in release mode on low core count systems with higher latency core types, so it has thus far defied most debugging attempts.  

Additional tests are needed to put further stress on the timing system as related to filters to make the bug more apparent.

**Comment by phlptp** [comment]
@nightlark How do I trigger a series of rebuilds on a branch on Appveyor?

**Comment by kdheepak** [comment]
It's possible that since the apppveyor builds are on a github user's account as opposed to the organization, only the user has permissions to trigger the build.

**Comment by nightlark** [comment]
It looks like Appveyor only has 2 options on their website, re-building the last commit, and creating new builds for the default branch. Triggering builds for other branches on Appveyor seems to only be possible with their api: https://gist.github.com/IlyaFinkelshteyn/a50029e48eccab12d0e16afe236d9274

If you sign into Appveyor with your GitHub account, you could do builds that are separate from the ones under my account.

**Comment by phlptp** [comment]
It looks like I can occasionally trigger the same issue on my system now in debug mode with a more complicated filter test.  That means I at least have some hope of resolving it using normal tools in the near future.  The checks I put in a couple days ago did not work to detect the problem.

**Comment by phlptp** [comment]
We have not seen this issue in a while, so unless it comes up again in one of the branches that includes the multi Broker test cases I am going to call this closed.  Other issues are now coming up but they look different than this one.

**Comment by phlptp** [comment]
Haven't seen this in a while now so I am going to call it fixed
