### ISSUE TITLE
Documentation for player and recorder and other apps

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/HELICS-src#97]
While the code is mostly working there is limited documentation on the player and recorder apps.

**Comment by jcfuller1** [comment]
Include player, recorder, and tracer.

**Comment by phlptp** [comment]
What would you like the "tracer" to do exactly?  My current thinking is it is mostly like a recorder except it can't function as an standalone endpoint and no file storage capabilities, just display or a callback for some other processing.

**Comment by phlptp** [comment]
I am sure more improvements will be needed to the documentation but it is in place now
